[package]
name = "zetesis-sat"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
rayon.workspace = true
zetesis-cpu.workspace = true
zetesis-ferraris.workspace = true

[dev-dependencies]
zetesis-themelios.workspace = true
proptest = "1.11"

[lints]
workspace = true
