[package]
name = "zetesis-sat"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
rayon.workspace = true
self_cell.workspace = true
zetesis-cpu.workspace = true
zetesis-ferraris.workspace = true

[dev-dependencies]
zetesis-themelios.workspace = true
proptest = "1.11"
zetesis-test-support.workspace = true
zetesis-theory-support.workspace = true

[lints]
workspace = true
