//! Unchanged original programs and their complete, unprojected model sets.

pub const CASES: &[(&str, &[&[&str]])] = &[
    ("1=1.", &[&[]]),
    ("1==1.", &[&[]]),
    ("1=2.", &[]),
    ("1!=2.", &[&[]]),
    ("1<2.", &[&[]]),
    ("1<=1.", &[&[]]),
    ("2>1.", &[&[]]),
    ("2>=2.", &[&[]]),
    ("not 1=1.", &[]),
    ("not 1=2.", &[&[]]),
    ("not not 1=1.", &[&[]]),
    ("not not 1=2.", &[]),
    ("1<2<3.", &[&[]]),
    ("not 1<2<1.", &[&[]]),
    ("1<a.", &[&[]]),
    ("f(1)<f(2).", &[&[]]),
    ("(1,a)=(1,a).", &[&[]]),
    ("{p(1);p(2)}.R=S:-p(R),p(S).", &[&[], &["p(1)"], &["p(2)"]]),
    ("d(1).X=X+1:-d(X),not missing.", &[]),
    ("X=1:-X=1.", &[&[]]),
    (
        "d(1..2).1{at(P,V):d(V)}1:-d(P).P=Q:-at(P,V),at(Q,V).",
        &[
            &["d(1)", "d(2)", "at(1,1)", "at(2,2)"],
            &["d(1)", "d(2)", "at(1,2)", "at(2,1)"],
        ],
    ),
    ("#true.", &[&[]]),
    ("#false.", &[]),
    ("not #true.", &[]),
    ("not #false.", &[&[]]),
    ("not not #true.", &[&[]]),
    ("not not #false.", &[]),
    ("{a}.#true:-a.", &[&[], &["a"]]),
    ("{a}.#false:-a.", &[&[]]),
    ("{a}.not #true:-a.", &[&[]]),
    ("{a}.not #false:-a.", &[&[], &["a"]]),
    ("{a}.not not #true:-a.", &[&[], &["a"]]),
    ("{a}.not not #false:-a.", &[&[]]),
    ("#true|a.", &[&[]]),
    ("#false|a.", &[&["a"]]),
    ("not #true|a.", &[&["a"]]),
    ("not #false|a.", &[&[]]),
    ("not not #true|a.", &[&[]]),
    ("not not #false|a.", &[&["a"]]),
    ("#true|not a.", &[&[]]),
    ("#false|not a.", &[&[]]),
    ("#true|not not a.", &[&[]]),
    ("#false|not not a.", &[]),
    ("{a}.#false|not not a.", &[&["a"]]),
    ("#false| -a.", &[&["-a"]]),
    ("a.#false| -a.", &[]),
    ("#true| -a.", &[&[]]),
    ("{a}.#true:-1=#count{1:a}.", &[&[], &["a"]]),
    ("{a}.#false:-1=#count{1:a}.", &[&[]]),
    ("#true|p(1..2).", &[&[]]),
    ("#false|p(1..2).", &[&["p(1)", "p(2)"]]),
    ("#true|p(2..1).", &[&[]]),
    ("#false|p(2..1).", &[&[]]),
    ("#true|p(1;2).", &[&[]]),
    ("#false|p(1;2).", &[&["p(1)", "p(2)"]]),
    ("#true:#true;a:not #false.", &[&[]]),
    ("#false:#true;a:not not #true.", &[&["a"]]),
    ("d(1).#false|p(X+1):-d(X).", &[&["d(1)", "p(2)"]]),
    ("d(1).#true|p(X+1):-d(X).", &[&["d(1)"]]),
    ("{a}.#true|b:-not a.", &[&[], &["a"]]),
    ("{a}.#false|b:-not a.", &[&["b"], &["a"]]),
    ("#true|a.a:-a.", &[&[]]),
    ("#false|a.a:-a.", &[&["a"]]),
    ("0#min{word:#false}0:-#false.", &[&[]]),
    ("0#max{word:#false}0:-#false.", &[&[]]),
    ("0#min{word:#false}0.", &[]),
    ("0#max{word:#false}0.", &[]),
];
