//! Resolved tuple measures retain head permissions independently of their values.
//!
//! Abstract Gringo assigns missing/nonnumeric sum tuples weight zero and keeps
//! every positive head choice. Positive-only sums likewise retain nonpositive
//! numeric heads. Unbounded heads contain the choices without a measure bound.

pub(super) const CASES: &[(&str, &str)] = &[
    ("#sum{:a}<=0.", "{a}."),
    ("#sum+{:a}<=0.", "{a}."),
    ("#sum{:a}>=1.", "{a}.:-."),
    ("#sum+{:a}>=1.", "{a}.:-."),
    ("#count{:a}=1.", "a."),
    ("#sum{word:a}<=0.", "{a}."),
    ("#sum+{word:a}<=0.", "{a}."),
    ("#sum{#inf:a;#sup:b}<=0.", "{a;b}."),
    ("#sum+{#inf:a;#sup:b}<=0.", "{a;b}."),
    ("#sum{f(1):a;(1,2):b;\"s\":c}<=0.", "{a;b;c}."),
    ("#sum+{-f(1):a;():b;\"s\":c}<=0.", "{a;b;c}."),
    ("#sum{-2:a}<=0.", "{a}."),
    ("#sum{0:a}<=0.", "{a}."),
    ("#sum{2:a}<=0.", "{a}.:-a."),
    ("#sum+{0:a}<=0.", "{a}."),
    ("#sum+{2:a}<=0.", "{a}.:-a."),
    ("#sum{word:a;0:a}=0.", "{a}."),
    ("#sum{word:a;word:b}=0.", "{a;b}."),
    ("#sum{:a;:b}=0.", "{a;b}."),
    ("d(word).#sum{W:a:d(W)}=0.", "d(word).{a}."),
    ("#sum{word:a:a}=0.", "{a:a}."),
    ("{a}.#sum{word:not a}=0.", "{a}."),
    ("#sum{word:#true}=0.", ""),
    ("#sum{word:a}=1:-#false.", ""),
    ("0#sum{s:a}0:-#false.", ""),
    ("0#sum+{-1:a}0:-#false.", ""),
    ("0#sum{word:#false}0:-#false.", ""),
    ("0#sum+{word:#false}0:-#false.", ""),
    ("#sum+{-2:a}<=0.", "{a}."),
    ("2#sum+{-2:a;2:b}2.", "{a;b}.:-not b."),
    ("0#sum+{-2:a;2:b}0.", "{a;b}.:-b."),
    ("b.2#sum+{-2:a;2:b}2.", "b.{a;b}.:-not b."),
    ("#sum+{-2:a;word:b;0:c}=0.", "{a;b;c}."),
    ("#sum+{-2:a;-2:b}=0.", "{a;b}."),
    ("#sum+{-2,k:a;-2,l:a}=0.", "{a}."),
    (
        "d(-2;word;0).#sum+{W:p(W):d(W)}=0.",
        "d(-2;word;0).{p(-2);p(word);p(0)}.",
    ),
    ("{d}.#sum+{-2:a:d}=0.", "{d}.{a:d}."),
    ("{d}.#sum+{-2:a:not d}=0.", "{d}.{a:not d}."),
    ("#sum+{-2:a:a}=0.", "{a:a}."),
    ("#sum+{-2:a;word:b}.", "{a;b}."),
    ("#sum{:a}.", "{a}."),
    ("#min{:a}.", "{a}."),
    ("#max{:a}.", "{a}."),
    ("#count{:a}.", "{a}."),
    ("#sum+{:a}.", "{a}."),
    ("#sum{word:a}.", "{a}."),
    ("#sum+{word:a}.", "{a}."),
    ("#sum{-2:a}.", "{a}."),
    ("#sum{0:a}.", "{a}."),
    ("#sum{2:a}.", "{a}."),
    ("#sum+{-2:a}.", "{a}."),
    ("#sum+{0:a}.", "{a}."),
    ("#sum+{2:a}.", "{a}."),
    ("#min{word:a}.", "{a}."),
    ("#max{word:a}.", "{a}."),
    ("#sum{word:a;1:b}.", "{a;b}."),
    ("#sum+{word:a;1:b}.", "{a;b}."),
    ("#min{:a;1:b}.", "{a;b}."),
    ("#max{:a;1:b}.", "{a;b}."),
    ("{a}.#sum+{-2:not a}=0.", "{a}."),
    ("#sum+{-2:not not a}=0.", "{not not a}."),
    ("#sum+{-2:#true}=0.", ""),
    ("#sum+{-2:a}=1:-#false.", ""),
    ("d(0..1).#sum+{-2:p(I)}=0:-d(I).", "d(0..1).{p(0);p(1)}."),
];

// A bounded extremum of a set containing empty tuples has no established
// total source interpretation. These original sources retain a named refusal.
pub(super) const REFUSED: &[&str] = &[
    "#min{:a}=#sup.",
    "#max{:a}=#inf.",
    "#min{:a}<=0.",
    "#max{:a}>=0.",
    "#min{:a;0:b}=0.",
    "#max{:a;0:b}=0.",
    "#min{:a;#sup:b}=#sup.",
    "#max{:a;#inf:b}=#inf.",
    "#min{:#true}=#sup.",
    "#max{:#false}=#inf.",
    "#max{:a}<=0.",
    "0#min{: #false}0:-#false.",
    "0#max{: #false}0:-#false.",
    "#min{:a}<=word.",
    "#max{:a}<=word.",
];

// Exact complete clingo 5.8.2 records that differ from the formal translation.
// These are comparisons with a documented source contract, not parity passes
// or an assertion that an upstream defect has been established.
pub(super) const CLINGO_DIFFERENCES: &[(&str, &[&[&str]])] = &[
    ("#sum{:a}<=0.", &[&[]]),
    ("#sum+{:a}<=0.", &[&[]]),
    ("#sum{word:a}<=0.", &[&[]]),
    ("#sum+{word:a}<=0.", &[&[]]),
    ("#sum{#inf:a;#sup:b}<=0.", &[&[]]),
    ("#sum+{#inf:a;#sup:b}<=0.", &[&[]]),
    ("#sum{f(1):a;(1,2):b;\"s\":c}<=0.", &[&[]]),
    ("#sum+{-f(1):a;():b;\"s\":c}<=0.", &[&[]]),
    ("#sum{word:a;word:b}=0.", &[&[]]),
    ("#sum{:a;:b}=0.", &[&[]]),
    ("d(word).#sum{W:a:d(W)}=0.", &[&["d(word)"]]),
    ("2#sum+{-2:a;2:b}2.", &[&["b"]]),
    ("0#sum+{-2:a;2:b}0.", &[&[], &["a"], &["a", "b"]]),
    (
        "#sum+{-2:a;word:b;0:c}=0.",
        &[&[], &["a"], &["a", "c"], &["c"]],
    ),
    (
        "d(-2;word;0).#sum+{W:p(W):d(W)}=0.",
        &[
            &["d(-2)", "d(0)", "d(word)"],
            &["d(-2)", "d(0)", "d(word)", "p(-2)"],
            &["d(-2)", "d(0)", "d(word)", "p(-2)", "p(0)"],
            &["d(-2)", "d(0)", "d(word)", "p(0)"],
        ],
    ),
    ("#sum{word:a}.", &[&[]]),
    ("#sum+{word:a}.", &[&[]]),
];
