import Zetesis

#print axioms Zetesis.AggregateAssignment.active_tuples_nodup
#print axioms Zetesis.AggregateAssignment.actual_tuple_sum_is_candidate
#print axioms Zetesis.AggregateAssignment.coalesced_active_tuples
#print axioms Zetesis.AggregateAssignment.coalescing_preserves_actual_sum
#print axioms Zetesis.AggregateAssignment.covered_actual_sum_is_candidate
#print axioms Zetesis.AggregateAssignment.eligible_for_iff_active
#print axioms Zetesis.AggregateAssignment.filter_nodup
#print axioms Zetesis.AggregateAssignment.filtered_sum_is_candidate
#print axioms Zetesis.AggregateAssignment.initial_zero_may_miss_actual_sum
#print axioms Zetesis.AggregateAssignment.mem_active_tuples
#print axioms Zetesis.AggregateAssignment.mem_unique
#print axioms Zetesis.AggregateAssignment.perm_weighted_sum
#print axioms Zetesis.AggregateAssignment.selected_sum_is_candidate
#print axioms Zetesis.AggregateAssignment.subset_candidates_need_not_be_realizable
#print axioms Zetesis.AggregateAssignment.subset_sums_length_le_pow
#print axioms Zetesis.AggregateAssignment.subset_sums_nodup
#print axioms Zetesis.AggregateAssignment.unique_length_le
#print axioms Zetesis.AggregateAssignment.unique_nodup
#print axioms Zetesis.BatchAccounting.commit_accounted
#print axioms Zetesis.BatchAccounting.commit_preserves_coverage
#print axioms Zetesis.BatchAccounting.commit_preserves_occurrences
#print axioms Zetesis.BatchAccounting.completed_results_exact
#print axioms Zetesis.BatchAccounting.delayed_error_prevents_exhaustion
#print axioms Zetesis.BatchAccounting.empty_pending_is_not_exhaustion
#print axioms Zetesis.BatchAccounting.exact_commit_preserves_soundness
#print axioms Zetesis.BatchAccounting.filter_partition_length
#print axioms Zetesis.BatchAccounting.hybrid_completion_exact
#print axioms Zetesis.BatchAccounting.initial_covers
#print axioms Zetesis.BatchAccounting.initial_sound
#print axioms Zetesis.BatchAccounting.pending_prevents_exhaustion
#print axioms Zetesis.BatchAccounting.prefix_membership
#print axioms Zetesis.BatchAccounting.proposal_preserves_coverage
#print axioms Zetesis.BatchAccounting.proposal_preserves_occurrences
#print axioms Zetesis.BatchAccounting.proposal_preserves_soundness
#print axioms Zetesis.BatchAccounting.propose_accounted
#print axioms Zetesis.Bounds.acceptance_survives_narrowing
#print axioms Zetesis.Bounds.accepted_seed_agrees
#print axioms Zetesis.Bounds.closed_upper_sound
#print axioms Zetesis.Bounds.conflicting_atom_refutes
#print axioms Zetesis.Bounds.consequence_sandwich
#print axioms Zetesis.Bounds.gamma_sandwich
#print axioms Zetesis.Bounds.gate_sandwich
#print axioms Zetesis.Bounds.inconsistent_narrowing_refutes
#print axioms Zetesis.Bounds.lower_constraint_refutes
#print axioms Zetesis.Bounds.lower_prefix_constraint_refutes
#print axioms Zetesis.Bounds.lower_prefix_sound
#print axioms Zetesis.Bounds.selected_consequence_mono
#print axioms Zetesis.Bounds.selected_consequence_refines
#print axioms Zetesis.CandidateCursor.accepted_outputs_exact
#print axioms Zetesis.CandidateCursor.complete_exact
#print axioms Zetesis.CandidateCursor.completed_coverage
#print axioms Zetesis.CandidateCursor.enough_fuel_no_interruption
#print axioms Zetesis.CandidateCursor.exhausted_all_blocked
#print axioms Zetesis.CandidateCursor.finite_completion_exists
#print axioms Zetesis.CandidateCursor.found_projection_partition
#print axioms Zetesis.CandidateCursor.found_sound
#print axioms Zetesis.CandidateCursor.interruption_retains_unblocked
#print axioms Zetesis.CandidateCursor.mem_eligible
#print axioms Zetesis.CandidateCursor.mem_projected_eligible
#print axioms Zetesis.CandidateCursor.next_preserves
#print axioms Zetesis.CandidateCursor.record_excludes_projection
#print axioms Zetesis.CandidateCursor.record_filters_remaining
#print axioms Zetesis.CandidateCursor.repeated_auxiliary_complete
#print axioms Zetesis.CandidateCursor.stable_outputs_exact
#print axioms Zetesis.CandidateCursor.zero_fuel_keeps_open_tree
#print axioms Zetesis.CertifiedExecution.completed_membership_exact
#print axioms Zetesis.CertifiedExecution.fallback_quota_is_cumulative
#print axioms Zetesis.CertifiedExecution.interruption_cannot_accept
#print axioms Zetesis.CertifiedExecution.ranked_support_verdict_sound
#print axioms Zetesis.CertifiedExecution.restricted_result_original
#print axioms Zetesis.CertifiedExecution.unsupported_requires_completion
#print axioms Zetesis.ChoiceIntervals.all_classical
#print axioms Zetesis.ChoiceIntervals.all_map_equivalent
#print axioms Zetesis.ChoiceIntervals.atLeast_classical
#print axioms Zetesis.ChoiceIntervals.atLeast_frozen
#print axioms Zetesis.ChoiceIntervals.atLeast_map_equivalent
#print axioms Zetesis.ChoiceIntervals.binding_length
#print axioms Zetesis.ChoiceIntervals.cardinality_constraints_frozen
#print axioms Zetesis.ChoiceIntervals.carrier_covers_exactly
#print axioms Zetesis.ChoiceIntervals.count_cons
#print axioms Zetesis.ChoiceIntervals.duplicate_head_eligibility
#print axioms Zetesis.ChoiceIntervals.duplicate_head_has_one_position
#print axioms Zetesis.ChoiceIntervals.eligibility_classical
#print axioms Zetesis.ChoiceIntervals.eligibility_frozen
#print axioms Zetesis.ChoiceIntervals.equivalent_conj
#print axioms Zetesis.ChoiceIntervals.equivalent_disj
#print axioms Zetesis.ChoiceIntervals.equivalent_imp
#print axioms Zetesis.ChoiceIntervals.equivalent_refl
#print axioms Zetesis.ChoiceIntervals.expanded_eligibility_classical
#print axioms Zetesis.ChoiceIntervals.expanded_eligibility_frozen
#print axioms Zetesis.ChoiceIntervals.expansion_group_classical
#print axioms Zetesis.ChoiceIntervals.expansion_group_equivalent
#print axioms Zetesis.ChoiceIntervals.expansion_group_frozen
#print axioms Zetesis.ChoiceIntervals.expansion_represents
#print axioms Zetesis.ChoiceIntervals.expansion_stable_in_context
#print axioms Zetesis.ChoiceIntervals.fresh_slot_indices_distinct
#print axioms Zetesis.ChoiceIntervals.fresh_slot_read
#print axioms Zetesis.ChoiceIntervals.group_classical
#print axioms Zetesis.ChoiceIntervals.group_equivalent
#print axioms Zetesis.ChoiceIntervals.headCarrier_nodup
#print axioms Zetesis.ChoiceIntervals.independent_occurrences_include_off_diagonal
#print axioms Zetesis.ChoiceIntervals.mem_headCarrier
#print axioms Zetesis.ChoiceIntervals.mem_interval
#print axioms Zetesis.ChoiceIntervals.negation_frozen
#print axioms Zetesis.ChoiceIntervals.positive_empty_group_is_constraint
#print axioms Zetesis.ChoiceIntervals.positive_reversed_expansion_is_constraint
#print axioms Zetesis.ChoiceIntervals.product_complete
#print axioms Zetesis.ChoiceIntervals.product_empty_at
#print axioms Zetesis.ChoiceIntervals.recursive_singleton_has_no_stable_model
#print axioms Zetesis.ChoiceIntervals.repeated_row_eligibility
#print axioms Zetesis.ChoiceIntervals.represented_eligibility_equivalent
#print axioms Zetesis.ChoiceIntervals.reversed_element_has_no_rows
#print axioms Zetesis.ChoiceIntervals.reversed_interval_empty
#print axioms Zetesis.ChoiceIntervals.splitting_bounded_group_changes_models
#print axioms Zetesis.ChoiceIntervals.substitute_equivalent
#print axioms Zetesis.ChoiceIntervals.tautological_eligibility_is_not_frozen_true
#print axioms Zetesis.ChoiceIntervals.unrelated_head_does_not_meet_lower_bound
#print axioms Zetesis.ClauseValidation.all_false_exact
#print axioms Zetesis.ClauseValidation.empty_clause_rejects
#print axioms Zetesis.ClauseValidation.first_true_after_prefix
#print axioms Zetesis.ClauseValidation.first_true_stops
#print axioms Zetesis.ClauseValidation.nonempty_suffix_strictly_saves_work
#print axioms Zetesis.ClauseValidation.scan_accepts_iff
#print axioms Zetesis.ClauseValidation.scan_empty
#print axioms Zetesis.ClauseValidation.scan_work_bound
#print axioms Zetesis.ClauseValidation.validate_accepts_iff
#print axioms Zetesis.ClauseValidation.validate_work_bound
#print axioms Zetesis.CountHeads.activity_frozen
#print axioms Zetesis.CountHeads.activity_original
#print axioms Zetesis.CountHeads.alias_directions_are_rejected
#print axioms Zetesis.CountHeads.bounds_are_candidate_constraints
#print axioms Zetesis.CountHeads.check_exact
#print axioms Zetesis.CountHeads.distinct_atoms_of_distinct_keys
#print axioms Zetesis.CountHeads.group_equivalent
#print axioms Zetesis.CountHeads.identical_duplicates_are_compatible
#print axioms Zetesis.CountHeads.stable_in_context
#print axioms Zetesis.CountHeads.table_atoms_nodup
#print axioms Zetesis.CountHeads.table_covers_atoms
#print axioms Zetesis.CoverageTree.exhausted_no_valid
#print axioms Zetesis.CoverageTree.mem_outputs_iff
#print axioms Zetesis.CoverageTree.outputs_complete
#print axioms Zetesis.CoverageTree.outputs_nodup
#print axioms Zetesis.CoverageTree.outputs_sound
#print axioms Zetesis.Cube.consequence_narrow_preserves
#print axioms Zetesis.Cube.contains_narrow
#print axioms Zetesis.Cube.contains_singleton
#print axioms Zetesis.Cube.contains_splitFalse
#print axioms Zetesis.Cube.contains_splitTrue
#print axioms Zetesis.Cube.fresh_branches
#print axioms Zetesis.Cube.narrow_preserves_valid
#print axioms Zetesis.Cube.split_disjoint
#print axioms Zetesis.Cube.split_partition
#print axioms Zetesis.DagSharing.decode_append
#print axioms Zetesis.DagSharing.exact_choice_graph_sharing
#print axioms Zetesis.DagSharing.findNode_complete
#print axioms Zetesis.DagSharing.findNode_sound
#print axioms Zetesis.DagSharing.fold_length
#print axioms Zetesis.DagSharing.getD_append_left
#print axioms Zetesis.DagSharing.getD_snoc_end
#print axioms Zetesis.DagSharing.intern_correct
#print axioms Zetesis.DagSharing.intern_existing_reuses
#print axioms Zetesis.DagSharing.meanings_length
#print axioms Zetesis.DagSharing.meanings_snoc
#print axioms Zetesis.DagSharing.reindex_meaning
#print axioms Zetesis.DagSharing.reindex_valid
#print axioms Zetesis.DagSharing.represented_theory_equal
#print axioms Zetesis.DagSharing.share_into_correct
#print axioms Zetesis.DagSharing.sharing_models_iff
#print axioms Zetesis.DagSharing.sharing_reduct_models_iff
#print axioms Zetesis.DagSharing.sharing_stable_iff
#print axioms Zetesis.DagSharing.sharing_theory_equal
#print axioms Zetesis.DagSharing.step_correct
#print axioms Zetesis.DagSharing.stored_meaning
#print axioms Zetesis.DagSharing.valid_mono
#print axioms Zetesis.DagSharing.well_formed_reference
#print axioms Zetesis.EventCounterexamples.empty_trace_legal
#print axioms Zetesis.EventCounterexamples.empty_trace_not_closed
#print axioms Zetesis.EventCounterexamples.factOperator_monotone
#print axioms Zetesis.EventCounterexamples.self_support_closed
#print axioms Zetesis.EventCounterexamples.self_support_has_no_complete_full_trace
#print axioms Zetesis.EventCounterexamples.self_support_least_empty
#print axioms Zetesis.EventCounterexamples.self_support_not_sound
#print axioms Zetesis.Examples.choice_consequence
#print axioms Zetesis.Examples.choice_empty_stable
#print axioms Zetesis.Examples.choice_full_stable
#print axioms Zetesis.Examples.choice_gamma
#print axioms Zetesis.Examples.choice_gamma_not_antimonotone
#print axioms Zetesis.Examples.fact_constraint_consequence
#print axioms Zetesis.Examples.fact_constraint_gamma
#print axioms Zetesis.Examples.fact_constraint_stable
#print axioms Zetesis.Examples.missing_constraint_gate_loses_model
#print axioms Zetesis.Examples.missing_constraint_gate_not_carrier
#print axioms Zetesis.ExtremumCandidates.candidate_length
#print axioms Zetesis.ExtremumCandidates.choose_is_input
#print axioms Zetesis.ExtremumCandidates.complete_candidate_coverage
#print axioms Zetesis.ExtremumCandidates.empty_maximum_is_infimum
#print axioms Zetesis.ExtremumCandidates.empty_minimum_is_supremum
#print axioms Zetesis.ExtremumCandidates.extreme_none_iff
#print axioms Zetesis.ExtremumCandidates.extreme_some_mem
#print axioms Zetesis.ExtremumCandidates.finite_ne_infimum
#print axioms Zetesis.ExtremumCandidates.finite_ne_supremum
#print axioms Zetesis.Feedback.all_feedback_preserves_stability
#print axioms Zetesis.Feedback.allow_iff_no_countermodel
#print axioms Zetesis.Feedback.classical_minimal_stable_sub_equal
#print axioms Zetesis.Feedback.cone_filter_exact
#print axioms Zetesis.Feedback.countermodel_excludes_candidate
#print axioms Zetesis.Feedback.excluded_has_countermodel
#print axioms Zetesis.Feedback.feedback_preserves_stability
#print axioms Zetesis.Feedback.other_stable_outside_cones
#print axioms Zetesis.Feedback.proper_subset_not_classical_model
#print axioms Zetesis.Feedback.proper_superset_not_stable
#print axioms Zetesis.Feedback.recorded_countermodel_excludes_candidate
#print axioms Zetesis.Feedback.stable_allows
#print axioms Zetesis.Feedback.stable_allows_all
#print axioms Zetesis.Feedback.unit_choice_comparable_stable_models
#print axioms Zetesis.Feedback.unit_choice_empty_stable
#print axioms Zetesis.Feedback.unit_choice_full_stable
#print axioms Zetesis.Feedback.unit_choice_not_classically_minimal
#print axioms Zetesis.Feedback.unit_choice_reduct_models
#print axioms Zetesis.Feedback.witness_exact
#print axioms Zetesis.Feedback.witness_theory_exact
#print axioms Zetesis.Ferraris.atom_reduct
#print axioms Zetesis.Ferraris.choice_reduct_guard
#print axioms Zetesis.Ferraris.double_neg_atom_reduct
#print axioms Zetesis.Ferraris.double_neg_formula_reduct
#print axioms Zetesis.Ferraris.double_neg_reduct_eq_truth
#print axioms Zetesis.Ferraris.double_neg_satisfies
#print axioms Zetesis.Ferraris.example_is_full_reduct
#print axioms Zetesis.Ferraris.incomparable_minimal_models
#print axioms Zetesis.Ferraris.masked_eval_iff_reduct
#print axioms Zetesis.Ferraris.masked_models_iff_reduct
#print axioms Zetesis.Ferraris.models_cons
#print axioms Zetesis.Ferraris.models_reduct_cons_double_neg
#print axioms Zetesis.Ferraris.models_reduct_self
#print axioms Zetesis.Ferraris.neg_atom_reduct
#print axioms Zetesis.Ferraris.no_least_model
#print axioms Zetesis.Ferraris.only_false_minimal
#print axioms Zetesis.Ferraris.only_true_minimal
#print axioms Zetesis.Ferraris.reduct_has_no_least_model
#print axioms Zetesis.Ferraris.reduct_self
#print axioms Zetesis.Ferraris.stable_cons_double_neg_iff
#print axioms Zetesis.Ferraris.stable_cons_double_neg_iff_of_satisfies
#print axioms Zetesis.Ferraris.stable_guard_theory_iff
#print axioms Zetesis.Ferraris.stable_guard_theory_iff_of_stable_entails
#print axioms Zetesis.Ferraris.stable_iff_masked_minimality
#print axioms Zetesis.Ferraris.stable_iff_minimal_reduct
#print axioms Zetesis.FiniteBindings.candidate_membership
#print axioms Zetesis.FiniteBindings.candidate_specification
#print axioms Zetesis.FiniteBindings.compiled_membership
#print axioms Zetesis.FiniteBindings.formula_membership
#print axioms Zetesis.FiniteBindings.frozen_in_context
#print axioms Zetesis.FiniteBindings.original_in_context
#print axioms Zetesis.FiniteBindings.stable_in_context
#print axioms Zetesis.FiniteBindings.strict_endpoints
#print axioms Zetesis.FiniteBindings.tighten_membership
#print axioms Zetesis.FinitePools.duplicate_alternative
#print axioms Zetesis.FinitePools.empty_occurrence
#print axioms Zetesis.FinitePools.flattening_changes_original_truth
#print axioms Zetesis.FinitePools.frozen_in_context
#print axioms Zetesis.FinitePools.independent_equal_occurrences
#print axioms Zetesis.FinitePools.original_in_context
#print axioms Zetesis.FinitePools.product_complete
#print axioms Zetesis.FinitePools.stable_in_context
#print axioms Zetesis.GroundGuards.chain_evaluation
#print axioms Zetesis.GroundGuards.classical_tautology_is_not_a_guard_replacement
#print axioms Zetesis.GroundGuards.constant_frozen
#print axioms Zetesis.GroundGuards.constant_original
#print axioms Zetesis.GroundGuards.double_negative_chain_scope
#print axioms Zetesis.GroundGuards.evaluated_guard_equivalent
#print axioms Zetesis.GroundGuards.guard_frozen
#print axioms Zetesis.GroundGuards.guard_original
#print axioms Zetesis.GroundGuards.negating_each_comparison_is_different
#print axioms Zetesis.GroundGuards.negative_chain_scope
#print axioms Zetesis.GroundGuards.replacement_in_formula_context
#print axioms Zetesis.GroundGuards.replacement_preserves_stability
#print axioms Zetesis.IndexedCandidates.block_exact
#print axioms Zetesis.IndexedCandidates.failed_literal_forced
#print axioms Zetesis.IndexedCandidates.failed_literal_query_exact
#print axioms Zetesis.IndexedCandidates.frozen_countermodel_probe_exact
#print axioms Zetesis.IndexedCandidates.identical_projection_same_filter
#print axioms Zetesis.IndexedCandidates.index_equals_all_blocks
#print axioms Zetesis.IndexedCandidates.lookup_empty
#print axioms Zetesis.IndexedCandidates.lookup_index
#print axioms Zetesis.IndexedCandidates.lookup_insert
#print axioms Zetesis.IndexedCandidates.recorded_projection_rejected
#print axioms Zetesis.IndexedCandidates.unseen_projection_allowed
#print axioms Zetesis.Lifted.bind_monotone
#print axioms Zetesis.Lifted.certified_materializer_exact
#print axioms Zetesis.Lifted.composition_exact
#print axioms Zetesis.Lifted.empty_snapshot_covered
#print axioms Zetesis.Lifted.family_closedness_exact
#print axioms Zetesis.Lifted.family_exact
#print axioms Zetesis.Lifted.filter_gate_commute
#print axioms Zetesis.Lifted.gate_pushdown_exact
#print axioms Zetesis.Lifted.grown_snapshot_not_covered
#print axioms Zetesis.Lifted.lazy_stages_exact
#print axioms Zetesis.Lifted.lazy_step_exact
#print axioms Zetesis.Lifted.materialized_complete
#print axioms Zetesis.Lifted.materialized_constraint_exact
#print axioms Zetesis.Lifted.materialized_exact
#print axioms Zetesis.Lifted.materialized_replay_idempotent
#print axioms Zetesis.Lifted.materialized_selection_monotone
#print axioms Zetesis.Lifted.materialized_sound
#print axioms Zetesis.Lifted.necessary_gate_pushdown_exact
#print axioms Zetesis.Lifted.omissions_cover
#print axioms Zetesis.Lifted.omitted_new_consequence
#print axioms Zetesis.Lifted.ruleTransform_monotone
#print axioms Zetesis.LiftedBridge.completed_lazy_stage_accept_sound
#print axioms Zetesis.LiftedBridge.completed_lazy_stage_exact
#print axioms Zetesis.LiftedBridge.family_consequence_ground
#print axioms Zetesis.LiftedBridge.family_constraints_ground
#print axioms Zetesis.LiftedBridge.lazy_accept_sound
#print axioms Zetesis.LiftedBridge.lazy_gamma_ground
#print axioms Zetesis.LiftedBridge.lazy_stage_sound
#print axioms Zetesis.LiftedBridge.lifted_gamma_ground
#print axioms Zetesis.NegativeHeads.double_negative_literal_reduct
#print axioms Zetesis.NegativeHeads.guarded_theory_preserves_stable_models
#print axioms Zetesis.NegativeHeads.head_reduct_of_positive_kept
#print axioms Zetesis.NegativeHeads.negative_literal_reduct
#print axioms Zetesis.NegativeHeads.reduct_truth_requires_original
#print axioms Zetesis.NegativeHeads.stable_has_positive_producer
#print axioms Zetesis.NegativeHeads.stable_satisfies_support
#print axioms Zetesis.NegativeHeads.support_formula_truth
#print axioms Zetesis.ObjectiveBounds.bounded_best_is_global
#print axioms Zetesis.ObjectiveBounds.bounded_optimum_keeps_original_reduct
#print axioms Zetesis.ObjectiveBounds.bounded_ties_exact
#print axioms Zetesis.ObjectiveBounds.excluded_is_worse
#print axioms Zetesis.ObjectiveBounds.incumbent_survives
#print axioms Zetesis.ObjectiveBounds.mem_prune
#print axioms Zetesis.ObjectiveBounds.optimum_survives
#print axioms Zetesis.ObjectiveBounds.tighten
#print axioms Zetesis.ObjectiveDirections.collision_and_cancellation_examples
#print axioms Zetesis.ObjectiveDirections.compiled_cost_enabled
#print axioms Zetesis.ObjectiveDirections.conditions_for_active
#print axioms Zetesis.ObjectiveDirections.enabled_key_iff
#print axioms Zetesis.ObjectiveDirections.normalization_preserves_comparison
#print axioms Zetesis.ObjectiveDirections.normalization_preserves_cost
#print axioms Zetesis.ObjectiveDirections.normalization_preserves_optimal_models
#print axioms Zetesis.ObjectiveDirections.normalization_preserves_tie_list
#print axioms Zetesis.ObjectiveDirections.normalization_preserves_vector
#print axioms Zetesis.ObjectiveDirections.normalized_keys_unique
#print axioms Zetesis.ObjectiveDirections.normalized_optimum_retains_reduct
#print axioms Zetesis.ObjectiveDirections.opposite_directions_coalesce
#print axioms Zetesis.ObjectiveDirections.raw_cost_keys
#print axioms Zetesis.ObjectiveDirections.same_contribution_iff_key
#print axioms Zetesis.ObjectiveDirections.same_weight_directions_distinct
#print axioms Zetesis.ObjectiveDirections.weighted_filter
#print axioms Zetesis.ObjectiveDirections.weighted_map
#print axioms Zetesis.Optimization.best_none_iff
#print axioms Zetesis.Optimization.best_spec
#print axioms Zetesis.Optimization.completed_best_is_optimal
#print axioms Zetesis.Optimization.completed_ties_exact
#print axioms Zetesis.Optimization.constant_on_stable_iff
#print axioms Zetesis.Optimization.optimal_is_minimal_reduct
#print axioms Zetesis.Optimization.optimal_is_stable
#print axioms Zetesis.Outcomes.completed_unsatisfiable_iff_empty
#print axioms Zetesis.Outcomes.delivered_values_are_valid
#print axioms Zetesis.Outcomes.empty_delivery_can_hide_a_valid_model
#print axioms Zetesis.Propagation.disabled_gate_leaves_inputs_free
#print axioms Zetesis.Propagation.disabled_implication_must_not_be_enforced
#print axioms Zetesis.Propagation.empty_candidate_has_no_proper_tested_world
#print axioms Zetesis.Propagation.empty_domain_refutes
#print axioms Zetesis.Propagation.enabled_gate_full_equivalence
#print axioms Zetesis.Propagation.finite_sweeps_models_iff
#print axioms Zetesis.Propagation.full_and_equivalence_propagates_backwards
#print axioms Zetesis.Propagation.gate_constraint_exact
#print axioms Zetesis.Propagation.gate_rows_exact
#print axioms Zetesis.Propagation.inner_query_exact
#print axioms Zetesis.Propagation.narrow_decreases
#print axioms Zetesis.Propagation.narrow_models_iff
#print axioms Zetesis.Propagation.narrow_monotone
#print axioms Zetesis.Propagation.narrow_retains_completion
#print axioms Zetesis.Propagation.parallel_round_models_iff
#print axioms Zetesis.Propagation.parity_projection_is_quiescent
#print axioms Zetesis.Propagation.propagated_conflict_establishes_stability
#print axioms Zetesis.Propagation.propagated_conflict_with_auxiliaries
#print axioms Zetesis.Propagation.proper_subset_domains_exact
#print axioms Zetesis.Propagation.quiescent_unknown_can_be_unsatisfiable
#print axioms Zetesis.Propagation.stale_projection_retains_completion
#print axioms Zetesis.Propagation.strict_drop_exact
#print axioms Zetesis.Propagation.subset_domains_exact
#print axioms Zetesis.Propagation.sweep_decreases
#print axioms Zetesis.Propagation.sweep_models_iff
#print axioms Zetesis.Propagation.sweep_retains_completion
#print axioms Zetesis.Propagation.unsupported_self_implication_is_not_stable
#print axioms Zetesis.QueryCompaction.and_clauses_commute
#print axioms Zetesis.QueryCompaction.and_clauses_exact
#print axioms Zetesis.QueryCompaction.assignment_branch_partition
#print axioms Zetesis.QueryCompaction.assignment_branches_disjoint
#print axioms Zetesis.QueryCompaction.boolean_implication_iff
#print axioms Zetesis.QueryCompaction.canonical_and_gate_exact
#print axioms Zetesis.QueryCompaction.compact_eval
#print axioms Zetesis.QueryCompaction.compact_gate_eval
#print axioms Zetesis.QueryCompaction.compacted_countermodels_iff
#print axioms Zetesis.QueryCompaction.compacted_gate_encoding_exact
#print axioms Zetesis.QueryCompaction.exhausted_branches_refute
#print axioms Zetesis.QueryCompaction.exists_boolean_representation
#print axioms Zetesis.QueryCompaction.formula_truth_iff
#print axioms Zetesis.QueryCompaction.gate_clauses_exact
#print axioms Zetesis.QueryCompaction.gate_clauses_unique_extension
#print axioms Zetesis.QueryCompaction.literal_negated_eval
#print axioms Zetesis.QueryCompaction.masked_query_eval_iff
#print axioms Zetesis.QueryCompaction.or_clauses_exact
#print axioms Zetesis.QueryCompaction.plan_query_eval
#print axioms Zetesis.QueryCompaction.query_models_iff_reduct
#print axioms Zetesis.QueryCompaction.reduct_query_eval_iff
#print axioms Zetesis.QueryCompaction.repeated_and_outputs_equal
#print axioms Zetesis.QueryCompaction.smart_gate_eval
#print axioms Zetesis.QueryCompaction.smart_negated_eval
#print axioms Zetesis.QueryCompaction.stable_iff_compacted_queries
#print axioms Zetesis.QueryCompaction.wire_negated_eval
#print axioms Zetesis.RuleFactorization.false_reduct
#print axioms Zetesis.RuleFactorization.frozen_factorization
#print axioms Zetesis.RuleFactorization.frozen_in_context
#print axioms Zetesis.RuleFactorization.models_append
#print axioms Zetesis.RuleFactorization.models_pairs
#print axioms Zetesis.RuleFactorization.original_factorization
#print axioms Zetesis.RuleFactorization.original_in_context
#print axioms Zetesis.RuleFactorization.reduct_any
#print axioms Zetesis.RuleFactorization.reduct_conj
#print axioms Zetesis.RuleFactorization.reduct_disj
#print axioms Zetesis.RuleFactorization.reduct_imp
#print axioms Zetesis.RuleFactorization.reduct_models_pairs
#print axioms Zetesis.RuleFactorization.satisfies_any
#print axioms Zetesis.RuleFactorization.stable_in_context
#print axioms Zetesis.Semantics.accept_sound
#print axioms Zetesis.Semantics.accepted_seed_in_carrier
#print axioms Zetesis.Semantics.accepted_seed_unique
#print axioms Zetesis.Semantics.body_mono
#print axioms Zetesis.Semantics.consequence_eq_on
#print axioms Zetesis.Semantics.consequence_mono
#print axioms Zetesis.Semantics.constraints_down
#print axioms Zetesis.Semantics.constraints_eq_on
#print axioms Zetesis.Semantics.finite_convergence_of_cover
#print axioms Zetesis.Semantics.finite_normalized_program_converges
#print axioms Zetesis.Semantics.gamma_closed
#print axioms Zetesis.Semantics.gamma_covered_by_programHeads
#print axioms Zetesis.Semantics.gamma_eq_omegaIter
#print axioms Zetesis.Semantics.gamma_eq_on
#print axioms Zetesis.Semantics.gamma_iff_finiteIter
#print axioms Zetesis.Semantics.gamma_le
#print axioms Zetesis.Semantics.gate_eq_on
#print axioms Zetesis.Semantics.omegaIter_consequence_closed
#print axioms Zetesis.Semantics.stable_complete
#print axioms Zetesis.Semantics.stable_iff_exists_seed
#print axioms Zetesis.Semantics.stable_iff_gamma
#print axioms Zetesis.SignedObjectiveBounds.candidate_filter_exact
#print axioms Zetesis.SignedObjectiveBounds.coalescing_order_example
#print axioms Zetesis.SignedObjectiveBounds.compiled_cost_exact
#print axioms Zetesis.SignedObjectiveBounds.completed_scalar_ties_exact
#print axioms Zetesis.SignedObjectiveBounds.contribution_exact
#print axioms Zetesis.SignedObjectiveBounds.magnitude_nonnegative
#print axioms Zetesis.SignedObjectiveBounds.mixed_cost_exact
#print axioms Zetesis.SignedObjectiveBounds.nonnegative_cost_nonnegative
#print axioms Zetesis.SignedObjectiveBounds.normalization_preserves_comparison
#print axioms Zetesis.SignedObjectiveBounds.normalization_preserves_optimal_models
#print axioms Zetesis.SignedObjectiveBounds.normalization_preserves_tie_list
#print axioms Zetesis.SignedObjectiveBounds.normalization_preserves_vector_equality
#print axioms Zetesis.SignedObjectiveBounds.optimal_survives_incumbent
#print axioms Zetesis.SignedObjectiveBounds.shifted_eq
#print axioms Zetesis.SignedObjectiveBounds.shifted_le
#print axioms Zetesis.SignedObjectiveBounds.shifted_lt
#print axioms Zetesis.SignedObjectiveBounds.shifted_vector_comparison
#print axioms Zetesis.StrongNegation.bounded_group_frozen
#print axioms Zetesis.StrongNegation.bounded_group_stable_in_context
#print axioms Zetesis.StrongNegation.coherence_classical
#print axioms Zetesis.StrongNegation.coherence_frozen
#print axioms Zetesis.StrongNegation.coherence_stable_filter
#print axioms Zetesis.StrongNegation.coherent_iff_on_covered
#print axioms Zetesis.StrongNegation.coherent_iff_on_pair_covered
#print axioms Zetesis.StrongNegation.coherent_on_of_coherent
#print axioms Zetesis.StrongNegation.compiled_classical
#print axioms Zetesis.StrongNegation.compiled_frozen
#print axioms Zetesis.StrongNegation.compiled_push_classical
#print axioms Zetesis.StrongNegation.compiled_push_frozen
#print axioms Zetesis.StrongNegation.compiled_rejects_incoherent_candidate
#print axioms Zetesis.StrongNegation.compiled_stable
#print axioms Zetesis.StrongNegation.compiled_stable_of_pair_coverage
#print axioms Zetesis.StrongNegation.compiled_target_coherent_stable
#print axioms Zetesis.StrongNegation.compiled_target_stable
#print axioms Zetesis.StrongNegation.conflicting_facts_are_unsatisfiable
#print axioms Zetesis.StrongNegation.default_negative_frozen
#print axioms Zetesis.StrongNegation.encoded_polarity_distinct
#print axioms Zetesis.StrongNegation.frozen_rename
#print axioms Zetesis.StrongNegation.frozen_theory_rename
#print axioms Zetesis.StrongNegation.image_sub
#print axioms Zetesis.StrongNegation.independent_polarity_choices
#print axioms Zetesis.StrongNegation.models_rename
#print axioms Zetesis.StrongNegation.negative_fact_stable
#print axioms Zetesis.StrongNegation.omitted_registry_admits_incoherence
#print axioms Zetesis.StrongNegation.pair_coverage_from_upper
#print axioms Zetesis.StrongNegation.pair_covered_of_covered
#print axioms Zetesis.StrongNegation.polarity_distinct
#print axioms Zetesis.StrongNegation.pull_monotone
#print axioms Zetesis.StrongNegation.pull_push
#print axioms Zetesis.StrongNegation.push_monotone
#print axioms Zetesis.StrongNegation.reduct_rename
#print axioms Zetesis.StrongNegation.rename_default_negative
#print axioms Zetesis.StrongNegation.satisfies_rename
#print axioms Zetesis.StrongNegation.signed_choice_frozen
#print axioms Zetesis.StrongNegation.stable_push
#print axioms Zetesis.StrongNegation.stable_target_iff
#print axioms Zetesis.StrongNegation.stable_target_is_image
#print axioms Zetesis.StrongNegation.strong_is_not_default
#print axioms Zetesis.StrongNegation.subset_image
#print axioms Zetesis.Thresholds.threshold_bound_antitone
#print axioms Zetesis.Thresholds.threshold_query_exact
#print axioms Zetesis.Thresholds.threshold_sum_monotone
#print axioms Zetesis.TightPlans.body_reduct_of_positive
#print axioms Zetesis.TightPlans.negation_frozen
#print axioms Zetesis.TightPlans.original_of_reduct
#print axioms Zetesis.TightPlans.producer_forces_head
#print axioms Zetesis.TightPlans.producer_reduct_of_heads
#print axioms Zetesis.TightPlans.ranked_mono
#print axioms Zetesis.TightPlans.ranked_no_self
#print axioms Zetesis.TightPlans.ranked_support_contained
#print axioms Zetesis.TightPlans.ranked_support_stable
#print axioms Zetesis.TightPlans.reversed_choice_reduct_guard
#print axioms Zetesis.TightPlans.stable_iff_ranked_support
#print axioms Zetesis.TightPlans.stable_supported
#print axioms Zetesis.TrueHeads.condition_frozen
#print axioms Zetesis.TrueHeads.condition_original
#print axioms Zetesis.TrueHeads.empty_range_erases_whole_family
#print axioms Zetesis.TrueHeads.family_frozen
#print axioms Zetesis.TrueHeads.family_original
#print axioms Zetesis.TrueHeads.head_frozen
#print axioms Zetesis.TrueHeads.head_original
#print axioms Zetesis.TrueHeads.instances_complete
#print axioms Zetesis.TrueHeads.literal_frozen
#print axioms Zetesis.TrueHeads.literal_original
#print axioms Zetesis.TrueHeads.rule_frozen
#print axioms Zetesis.TrueHeads.rule_original
#print axioms Zetesis.TrueHeads.stable_has_positive_producer
#print axioms Zetesis.TrueHeads.stable_in_context
#print axioms Zetesis.UniversalConditionals.all_frozen
#print axioms Zetesis.UniversalConditionals.cross_candidate_reuse_changes_truth
#print axioms Zetesis.UniversalConditionals.empty_vacuity
#print axioms Zetesis.UniversalConditionals.erasing_true_antecedent_changes_frozen_truth
#print axioms Zetesis.UniversalConditionals.false_condition_vacuity
#print axioms Zetesis.UniversalConditionals.frozen_semantics
#print axioms Zetesis.UniversalConditionals.original_semantics
#print axioms Zetesis.UniversalConditionals.removal_frozen
#print axioms Zetesis.UniversalConditionals.removal_in_rule
#print axioms Zetesis.UniversalConditionals.removal_keeps_candidate_stability
#print axioms Zetesis.UniversalConditionals.removal_original
#print axioms Zetesis.UniversalConditionals.specialization_exact
#print axioms Zetesis.UniversalConditionals.specialization_keeps_candidate_stability
#print axioms Zetesis.UniversalConditionals.uniform_removal_on_domain
#print axioms Zetesis.ValueExtrema.candidate_length
#print axioms Zetesis.ValueExtrema.choose_is_input
#print axioms Zetesis.ValueExtrema.coalesced_witness_frozen
#print axioms Zetesis.ValueExtrema.coalesced_witness_original
#print axioms Zetesis.ValueExtrema.completed_candidate_coverage
#print axioms Zetesis.ValueExtrema.empty_result
#print axioms Zetesis.ValueExtrema.empty_witness_frozen
#print axioms Zetesis.ValueExtrema.empty_witness_original
#print axioms Zetesis.ValueExtrema.extreme_none_iff
#print axioms Zetesis.ValueExtrema.extreme_some_mem
#print axioms Zetesis.ValueExtrema.frozen_requires_original
#print axioms Zetesis.ValueExtrema.guard_congruence
#print axioms Zetesis.ValueExtrema.guard_frozen
#print axioms Zetesis.ValueExtrema.guard_original
#print axioms Zetesis.ValueExtrema.selected_or_empty_predicate
#print axioms Zetesis.ValueExtrema.selected_predicate
#print axioms Zetesis.ValueExtrema.witness_frozen
#print axioms Zetesis.ValueExtrema.witness_original
#print axioms Zetesis.accepted_sample_does_not_exhaust_region
#print axioms Zetesis.applyEvents_append
#print axioms Zetesis.applyEvents_grows
#print axioms Zetesis.applyEvents_prefix_grows
#print axioms Zetesis.atoms_ext
#print axioms Zetesis.batch_monotone
#print axioms Zetesis.completed_events_exact
#print axioms Zetesis.completed_events_order_independent
#print axioms Zetesis.compose_assoc
#print axioms Zetesis.compose_congr
#print axioms Zetesis.compose_monotone
#print axioms Zetesis.compose_refines
#print axioms Zetesis.duplicate_events_legal
#print axioms Zetesis.duplicate_events_same_state
#print axioms Zetesis.events_from_bottom_sound
#print axioms Zetesis.exact_of_sound_and_closed
#print axioms Zetesis.filter_image_pushdown
#print axioms Zetesis.filter_monotone
#print axioms Zetesis.finiteIter_exact_if_closed
#print axioms Zetesis.finiteIter_grows
#print axioms Zetesis.finiteIter_sound
#print axioms Zetesis.finiteIter_stage_mono
#print axioms Zetesis.finiteList_uniform_stage
#print axioms Zetesis.finiteList_uniform_stage_if
#print axioms Zetesis.fusion_preserves_least
#print axioms Zetesis.identity_monotone
#print axioms Zetesis.image_monotone
#print axioms Zetesis.insertAtom_contains
#print axioms Zetesis.insertAtom_duplicate
#print axioms Zetesis.insertAtom_grows
#print axioms Zetesis.insertAtom_idempotent
#print axioms Zetesis.insertAtom_sound
#print axioms Zetesis.inter_sub_left
#print axioms Zetesis.inter_sub_right
#print axioms Zetesis.least_batch
#print axioms Zetesis.least_closed
#print axioms Zetesis.least_congr
#print axioms Zetesis.least_fixed
#print axioms Zetesis.least_le
#print axioms Zetesis.least_mono
#print axioms Zetesis.legalEvents_append
#print axioms Zetesis.legalEvents_sound
#print axioms Zetesis.parallel_compose
#print axioms Zetesis.parallel_congr
#print axioms Zetesis.parallel_monotone
#print axioms Zetesis.parallel_refines
#print axioms Zetesis.rejected_sample_does_not_refute_region
#print axioms Zetesis.sub_antisymm
#print axioms Zetesis.sub_refl
#print axioms Zetesis.sub_trans
