import Zetesis

#print axioms Zetesis.AggregateAssignment.mem_unique
#print axioms Zetesis.AggregateAssignment.unique_nodup
#print axioms Zetesis.AggregateAssignment.unique_length_le
#print axioms Zetesis.AggregateAssignment.selected_sum_is_candidate
#print axioms Zetesis.AggregateAssignment.subset_sums_nodup
#print axioms Zetesis.AggregateAssignment.subset_sums_length_le_pow
#print axioms Zetesis.AggregateAssignment.perm_weighted_sum
#print axioms Zetesis.AggregateAssignment.filtered_sum_is_candidate
#print axioms Zetesis.AggregateAssignment.filter_nodup
#print axioms Zetesis.AggregateAssignment.covered_actual_sum_is_candidate
#print axioms Zetesis.AggregateAssignment.active_tuples_nodup
#print axioms Zetesis.AggregateAssignment.mem_active_tuples
#print axioms Zetesis.AggregateAssignment.eligible_for_iff_active
#print axioms Zetesis.AggregateAssignment.coalesced_active_tuples
#print axioms Zetesis.AggregateAssignment.coalescing_preserves_actual_sum
#print axioms Zetesis.AggregateAssignment.actual_tuple_sum_is_candidate
#print axioms Zetesis.AggregateAssignment.initial_zero_may_miss_actual_sum
#print axioms Zetesis.AggregateAssignment.subset_candidates_need_not_be_realizable
#print axioms Zetesis.AggregateBounds.active_bounds
#print axioms Zetesis.AggregateBounds.violated_bound_refutes
#print axioms Zetesis.AggregateBounds.inactive_frozen
#print axioms Zetesis.AggregateBounds.proposal_does_not_activate
#print axioms Zetesis.AggregateConsumers.available_iff
#print axioms Zetesis.AggregateConsumers.ready_split
#print axioms Zetesis.AggregateConsumers.scheduled_input_has_prior_producer
#print axioms Zetesis.AggregateConsumers.covered_consumer
#print axioms Zetesis.AggregateConsumers.original_clause
#print axioms Zetesis.AggregateConsumers.false_filter_frozen
#print axioms Zetesis.AggregateConsumers.frozen_consumer_identity
#print axioms Zetesis.AggregateConsumers.proposal_does_not_assert_head
#print axioms Zetesis.AggregateDependencies.row_membership
#print axioms Zetesis.AggregateDependencies.covered_extension
#print axioms Zetesis.AggregateDependencies.covered_sum
#print axioms Zetesis.AggregateDependencies.covered_continuation
#print axioms Zetesis.AggregateDependencies.appended_predecessors
#print axioms Zetesis.AggregateDependencies.original_rows
#print axioms Zetesis.AggregateDependencies.frozen_rows
#print axioms Zetesis.AggregateInvariants.sum_invariant
#print axioms Zetesis.AggregateInvariants.extremum_invariant
#print axioms Zetesis.AggregateInvariants.fixed_priority_presence
#print axioms Zetesis.AggregateRanges.sublist_envelope
#print axioms Zetesis.AggregateRanges.permutation_sum
#print axioms Zetesis.AggregateRanges.subcollection_range
#print axioms Zetesis.AggregateRanges.subcollection_of_sublist
#print axioms Zetesis.AggregateRanges.reduction_sum
#print axioms Zetesis.AggregateRanges.parallel_reduction_range
#print axioms Zetesis.AggregateRanges.bounded_total_is_insufficient
#print axioms Zetesis.AggregateReduct.masks_complete
#print axioms Zetesis.AggregateReduct.selected_forall
#print axioms Zetesis.AggregateReduct.selected_exists
#print axioms Zetesis.AggregateReduct.all_frozen
#print axioms Zetesis.AggregateReduct.clause_mask
#print axioms Zetesis.AggregateReduct.clause_original
#print axioms Zetesis.AggregateReduct.clause_frozen
#print axioms Zetesis.AggregateReduct.excluded_masks
#print axioms Zetesis.AggregateReduct.original
#print axioms Zetesis.AggregateReduct.frozen
#print axioms Zetesis.AggregateReduct.direct_reduct
#print axioms Zetesis.AggregateReduct.evaluator_refinement
#print axioms Zetesis.AtomKeys.missing_blocks_tuple
#print axioms Zetesis.AtomKeys.tuple_agrees
#print axioms Zetesis.AtomKeys.key_identity
#print axioms Zetesis.AtomKeys.membership_identity
#print axioms Zetesis.BatchAccounting.initial_covers
#print axioms Zetesis.BatchAccounting.initial_sound
#print axioms Zetesis.BatchAccounting.prefix_membership
#print axioms Zetesis.BatchAccounting.propose_accounted
#print axioms Zetesis.BatchAccounting.proposal_preserves_occurrences
#print axioms Zetesis.BatchAccounting.filter_partition_length
#print axioms Zetesis.BatchAccounting.commit_preserves_occurrences
#print axioms Zetesis.BatchAccounting.proposal_preserves_coverage
#print axioms Zetesis.BatchAccounting.proposal_preserves_soundness
#print axioms Zetesis.BatchAccounting.commit_accounted
#print axioms Zetesis.BatchAccounting.commit_preserves_coverage
#print axioms Zetesis.BatchAccounting.exact_commit_preserves_soundness
#print axioms Zetesis.BatchAccounting.completed_results_exact
#print axioms Zetesis.BatchAccounting.pending_prevents_exhaustion
#print axioms Zetesis.BatchAccounting.delayed_error_prevents_exhaustion
#print axioms Zetesis.BatchAccounting.empty_pending_is_not_exhaustion
#print axioms Zetesis.BatchAccounting.hybrid_completion_exact
#print axioms Zetesis.BinaryWatch.positions_exhausted
#print axioms Zetesis.BinaryWatch.replacement_absent
#print axioms Zetesis.BindingScopes.restrict_inside
#print axioms Zetesis.BindingScopes.restrict_outside
#print axioms Zetesis.BindingScopes.absent_is_not_value
#print axioms Zetesis.BindingScopes.absent_blocks_read
#print axioms Zetesis.BindingScopes.readAll_agrees
#print axioms Zetesis.BindingScopes.readAll_restrict
#print axioms Zetesis.BooleanHeadElements.operand_original
#print axioms Zetesis.BooleanHeadElements.operand_frozen
#print axioms Zetesis.BooleanHeadElements.boolean_keys_distinct
#print axioms Zetesis.BooleanHeadElements.boolean_witness_key
#print axioms Zetesis.BooleanHeadElements.atom_choice_key
#print axioms Zetesis.BooleanHeadElements.activity_original
#print axioms Zetesis.BooleanHeadElements.activity_frozen
#print axioms Zetesis.BooleanHeadElements.permission_original
#print axioms Zetesis.BooleanHeadElements.permission_frozen
#print axioms Zetesis.BooleanHeadElements.boolean_permission_frozen
#print axioms Zetesis.BooleanHeadElements.remove_boolean_permissions
#print axioms Zetesis.BooleanHeadElements.eligibility_original
#print axioms Zetesis.BooleanHeadElements.eligibility_frozen
#print axioms Zetesis.BooleanHeadElements.permissions_coalesced
#print axioms Zetesis.BooleanHeadElements.formula_original
#print axioms Zetesis.BooleanHeadElements.coalesced_group_in_context
#print axioms Zetesis.BooleanHeadElements.boolean_group_in_context
#print axioms Zetesis.BooleanHeadElements.same_rows_in_context
#print axioms Zetesis.BooleanHeads.constant_original
#print axioms Zetesis.BooleanHeads.constant_frozen
#print axioms Zetesis.BooleanHeads.negative_constant_frozen
#print axioms Zetesis.BooleanHeads.double_negative_constant_frozen
#print axioms Zetesis.BooleanHeads.head_reduct_of_positive_kept
#print axioms Zetesis.BooleanHeads.stable_has_positive_producer
#print axioms Zetesis.BooleanHeads.support_formula_truth
#print axioms Zetesis.BooleanHeads.stable_satisfies_support
#print axioms Zetesis.BooleanHeads.guarded_theory_preserves_stable_models
#print axioms Zetesis.Bounds.gate_sandwich
#print axioms Zetesis.Bounds.selected_consequence_mono
#print axioms Zetesis.Bounds.selected_consequence_refines
#print axioms Zetesis.Bounds.consequence_sandwich
#print axioms Zetesis.Bounds.gamma_sandwich
#print axioms Zetesis.Bounds.lower_prefix_sound
#print axioms Zetesis.Bounds.closed_upper_sound
#print axioms Zetesis.Bounds.accepted_seed_agrees
#print axioms Zetesis.Bounds.acceptance_survives_narrowing
#print axioms Zetesis.Bounds.inconsistent_narrowing_refutes
#print axioms Zetesis.Bounds.conflicting_atom_refutes
#print axioms Zetesis.Bounds.lower_constraint_refutes
#print axioms Zetesis.Bounds.lower_prefix_constraint_refutes
#print axioms Zetesis.CandidateCursor.next_preserves
#print axioms Zetesis.CandidateCursor.enough_fuel_no_interruption
#print axioms Zetesis.CandidateCursor.mem_eligible
#print axioms Zetesis.CandidateCursor.found_sound
#print axioms Zetesis.CandidateCursor.exhausted_all_blocked
#print axioms Zetesis.CandidateCursor.interruption_retains_unblocked
#print axioms Zetesis.CandidateCursor.record_excludes_projection
#print axioms Zetesis.CandidateCursor.mem_projected_eligible
#print axioms Zetesis.CandidateCursor.found_projection_partition
#print axioms Zetesis.CandidateCursor.record_filters_remaining
#print axioms Zetesis.CandidateCursor.finite_completion_exists
#print axioms Zetesis.CandidateCursor.complete_exact
#print axioms Zetesis.CandidateCursor.completed_coverage
#print axioms Zetesis.CandidateCursor.accepted_outputs_exact
#print axioms Zetesis.CandidateCursor.stable_outputs_exact
#print axioms Zetesis.CandidateCursor.repeated_auxiliary_complete
#print axioms Zetesis.CandidateCursor.zero_fuel_keeps_open_tree
#print axioms Zetesis.CertifiedExecution.ranked_support_verdict_sound
#print axioms Zetesis.CertifiedExecution.completed_membership_exact
#print axioms Zetesis.CertifiedExecution.interruption_cannot_accept
#print axioms Zetesis.CertifiedExecution.unsupported_requires_completion
#print axioms Zetesis.CertifiedExecution.fallback_quota_is_cumulative
#print axioms Zetesis.CertifiedExecution.restricted_result_original
#print axioms Zetesis.ChoiceConsumers.original_bounds
#print axioms Zetesis.ChoiceConsumers.rejected_frozen
#print axioms Zetesis.ChoiceConsumers.unrealized_frozen
#print axioms Zetesis.ChoiceConsumers.accepted_equivalent
#print axioms Zetesis.ChoiceConsumers.covered_bounds
#print axioms Zetesis.ChoiceConsumers.equal_bounds_frozen
#print axioms Zetesis.ChoiceIntervals.mem_interval
#print axioms Zetesis.ChoiceIntervals.reversed_interval_empty
#print axioms Zetesis.ChoiceIntervals.product_complete
#print axioms Zetesis.ChoiceIntervals.binding_length
#print axioms Zetesis.ChoiceIntervals.fresh_slot_read
#print axioms Zetesis.ChoiceIntervals.fresh_slot_indices_distinct
#print axioms Zetesis.ChoiceIntervals.independent_occurrences_include_off_diagonal
#print axioms Zetesis.ChoiceIntervals.expansion_represents
#print axioms Zetesis.ChoiceIntervals.eligibility_classical
#print axioms Zetesis.ChoiceIntervals.eligibility_frozen
#print axioms Zetesis.ChoiceIntervals.expanded_eligibility_classical
#print axioms Zetesis.ChoiceIntervals.expanded_eligibility_frozen
#print axioms Zetesis.ChoiceIntervals.equivalent_refl
#print axioms Zetesis.ChoiceIntervals.equivalent_conj
#print axioms Zetesis.ChoiceIntervals.equivalent_disj
#print axioms Zetesis.ChoiceIntervals.equivalent_imp
#print axioms Zetesis.ChoiceIntervals.substitute_equivalent
#print axioms Zetesis.ChoiceIntervals.represented_eligibility_equivalent
#print axioms Zetesis.ChoiceIntervals.count_cons
#print axioms Zetesis.ChoiceIntervals.atLeast_classical
#print axioms Zetesis.ChoiceIntervals.atLeast_frozen
#print axioms Zetesis.ChoiceIntervals.all_classical
#print axioms Zetesis.ChoiceIntervals.all_map_equivalent
#print axioms Zetesis.ChoiceIntervals.atLeast_map_equivalent
#print axioms Zetesis.ChoiceIntervals.group_equivalent
#print axioms Zetesis.ChoiceIntervals.group_classical
#print axioms Zetesis.ChoiceIntervals.headCarrier_nodup
#print axioms Zetesis.ChoiceIntervals.mem_headCarrier
#print axioms Zetesis.ChoiceIntervals.carrier_covers_exactly
#print axioms Zetesis.ChoiceIntervals.expansion_group_equivalent
#print axioms Zetesis.ChoiceIntervals.expansion_group_classical
#print axioms Zetesis.ChoiceIntervals.expansion_group_frozen
#print axioms Zetesis.ChoiceIntervals.expansion_stable_in_context
#print axioms Zetesis.ChoiceIntervals.product_empty_at
#print axioms Zetesis.ChoiceIntervals.reversed_element_has_no_rows
#print axioms Zetesis.ChoiceIntervals.positive_empty_group_is_constraint
#print axioms Zetesis.ChoiceIntervals.positive_reversed_expansion_is_constraint
#print axioms Zetesis.ChoiceIntervals.duplicate_head_eligibility
#print axioms Zetesis.ChoiceIntervals.duplicate_head_has_one_position
#print axioms Zetesis.ChoiceIntervals.repeated_row_eligibility
#print axioms Zetesis.ChoiceIntervals.tautological_eligibility_is_not_frozen_true
#print axioms Zetesis.ChoiceIntervals.splitting_bounded_group_changes_models
#print axioms Zetesis.ChoiceIntervals.negation_frozen
#print axioms Zetesis.ChoiceIntervals.cardinality_constraints_frozen
#print axioms Zetesis.ChoiceIntervals.recursive_singleton_has_no_stable_model
#print axioms Zetesis.ChoiceIntervals.unrelated_head_does_not_meet_lower_bound
#print axioms Zetesis.ClauseValidation.scan_empty
#print axioms Zetesis.ClauseValidation.scan_accepts_iff
#print axioms Zetesis.ClauseValidation.scan_work_bound
#print axioms Zetesis.ClauseValidation.first_true_stops
#print axioms Zetesis.ClauseValidation.all_false_exact
#print axioms Zetesis.ClauseValidation.first_true_after_prefix
#print axioms Zetesis.ClauseValidation.nonempty_suffix_strictly_saves_work
#print axioms Zetesis.ClauseValidation.validate_accepts_iff
#print axioms Zetesis.ClauseValidation.validate_work_bound
#print axioms Zetesis.ClauseValidation.empty_clause_rejects
#print axioms Zetesis.ColumnRelations.encoding_exact
#print axioms Zetesis.ColumnRelations.identifier_equality
#print axioms Zetesis.ColumnRelations.reconstruction_exact
#print axioms Zetesis.ColumnRelations.accepts_exact
#print axioms Zetesis.ColumnRelations.selection_exact
#print axioms Zetesis.ColumnRelations.selection_subsequence
#print axioms Zetesis.ColumnRelations.selection_increasing
#print axioms Zetesis.ColumnRelations.no_equalities_preserve_input
#print axioms Zetesis.ColumnRelations.absent_value_selects_nothing
#print axioms Zetesis.ColumnRelations.full_matches_preserved
#print axioms Zetesis.ColumnRelations.source_posting_exact
#print axioms Zetesis.ColumnRelations.row_mask_roundtrip
#print axioms Zetesis.ColumnRelations.applicability_exact
#print axioms Zetesis.ConditionalConsumers.original_body
#print axioms Zetesis.ConditionalConsumers.frozen_body
#print axioms Zetesis.ConditionalConsumers.empty_body_equivalent
#print axioms Zetesis.ConditionalConsumers.unrealized_rule_frozen
#print axioms Zetesis.ConditionalConsumers.covered_conditionals
#print axioms Zetesis.ConsequentAlternatives.original_semantics
#print axioms Zetesis.ConsequentAlternatives.frozen_semantics
#print axioms Zetesis.ConsequentAlternatives.candidate_consequents
#print axioms Zetesis.ConsequentAlternatives.empty_rows_original
#print axioms Zetesis.ConsequentAlternatives.empty_rows_frozen
#print axioms Zetesis.ConsequentAlternatives.empty_alternatives_original
#print axioms Zetesis.ConsequentAlternatives.empty_alternatives_frozen
#print axioms Zetesis.ConsequentAlternatives.polarity_placement_changes_truth
#print axioms Zetesis.ConsequentAlternatives.alternative_collection_keeps_stability
#print axioms Zetesis.ConstructorPatterns.function_shape_exact
#print axioms Zetesis.ConstructorPatterns.tuple_refuses_function
#print axioms Zetesis.ConstructorPatterns.root_capture
#print axioms Zetesis.ConstructorPatterns.function_child
#print axioms Zetesis.ConstructorPatterns.extraction_sound
#print axioms Zetesis.ConstructorPatterns.extraction_complete
#print axioms Zetesis.ConstructorPatterns.successful_shapes
#print axioms Zetesis.ConstructorPatterns.binding_sound
#print axioms Zetesis.ConstructorPatterns.acceptance_iff_consistent
#print axioms Zetesis.ConstructorPatterns.failure_preserves_binding
#print axioms Zetesis.sub_refl
#print axioms Zetesis.sub_trans
#print axioms Zetesis.atoms_ext
#print axioms Zetesis.sub_antisymm
#print axioms Zetesis.inter_sub_left
#print axioms Zetesis.inter_sub_right
#print axioms Zetesis.CountEligibility.key_iff_atom
#print axioms Zetesis.CountEligibility.indexed_rows_equal
#print axioms Zetesis.CountEligibility.activity_original
#print axioms Zetesis.CountEligibility.activity_frozen
#print axioms Zetesis.CountEligibility.activity_equivalent
#print axioms Zetesis.CountEligibility.threshold_equivalent
#print axioms Zetesis.CountEligibility.eligibility_equal
#print axioms Zetesis.CountHeadActivity.activity_original
#print axioms Zetesis.CountHeadActivity.activity_frozen
#print axioms Zetesis.CountHeadActivity.eligibility_original
#print axioms Zetesis.CountHeadActivity.eligibility_frozen
#print axioms Zetesis.CountHeadActivity.activity_of_same_rows
#print axioms Zetesis.CountHeadActivity.eligibility_of_same_rows
#print axioms Zetesis.CountHeadActivity.threshold_original
#print axioms Zetesis.CountHeadActivity.bounds_are_candidate_constraints
#print axioms Zetesis.CountHeadActivity.stable_in_context
#print axioms Zetesis.CountHeads.check_exact
#print axioms Zetesis.CountHeads.distinct_atoms_of_distinct_keys
#print axioms Zetesis.CountHeads.table_atoms_nodup
#print axioms Zetesis.CountHeads.table_covers_atoms
#print axioms Zetesis.CountHeads.activity_original
#print axioms Zetesis.CountHeads.activity_frozen
#print axioms Zetesis.CountHeads.group_equivalent
#print axioms Zetesis.CountHeads.stable_in_context
#print axioms Zetesis.CountHeads.bounds_are_candidate_constraints
#print axioms Zetesis.CountHeads.alias_directions_are_rejected
#print axioms Zetesis.CountHeads.identical_duplicates_are_compatible
#print axioms Zetesis.DagSharing.getD_append_left
#print axioms Zetesis.DagSharing.getD_snoc_end
#print axioms Zetesis.DagSharing.fold_length
#print axioms Zetesis.DagSharing.meanings_length
#print axioms Zetesis.DagSharing.meanings_snoc
#print axioms Zetesis.DagSharing.decode_append
#print axioms Zetesis.DagSharing.well_formed_reference
#print axioms Zetesis.DagSharing.valid_mono
#print axioms Zetesis.DagSharing.stored_meaning
#print axioms Zetesis.DagSharing.findNode_sound
#print axioms Zetesis.DagSharing.intern_correct
#print axioms Zetesis.DagSharing.reindex_valid
#print axioms Zetesis.DagSharing.reindex_meaning
#print axioms Zetesis.DagSharing.step_correct
#print axioms Zetesis.DagSharing.share_into_correct
#print axioms Zetesis.DagSharing.represented_theory_equal
#print axioms Zetesis.DagSharing.sharing_theory_equal
#print axioms Zetesis.DagSharing.sharing_models_iff
#print axioms Zetesis.DagSharing.sharing_reduct_models_iff
#print axioms Zetesis.DagSharing.sharing_stable_iff
#print axioms Zetesis.DagSharing.findNode_complete
#print axioms Zetesis.DagSharing.intern_existing_reuses
#print axioms Zetesis.DagSharing.exact_choice_graph_sharing
#print axioms Zetesis.DeltaJoins.first_true
#print axioms Zetesis.DeltaJoins.partition_complete
#print axioms Zetesis.DeltaJoins.partition_disjoint
#print axioms Zetesis.DisjunctiveSupport.head_satisfies
#print axioms Zetesis.DisjunctiveSupport.head_reduct
#print axioms Zetesis.DisjunctiveSupport.other_head
#print axioms Zetesis.DisjunctiveSupport.producer_removal
#print axioms Zetesis.DisjunctiveSupport.answer_set_supported
#print axioms Zetesis.DomainContraction.singleton_filter_preserves
#print axioms Zetesis.DomainContraction.remainder_lower_bound
#print axioms Zetesis.DomainContraction.affine_filter_preserves
#print axioms Zetesis.DomainContraction.contraction_decreases
#print axioms Zetesis.DomainContraction.compatible_contraction
#print axioms Zetesis.DomainContraction.bounded_filters_preserve_completions
#print axioms Zetesis.DomainContraction.empty_domain_excludes_completions
#print axioms Zetesis.EvaluatedWitnesses.successful_selection
#print axioms Zetesis.EvaluatedWitnesses.completed_condition_preserved
#print axioms Zetesis.EvaluatedWitnesses.undefined_selection
#print axioms Zetesis.EvaluatedWitnesses.unmatched_row_skips_evaluation
#print axioms Zetesis.EvaluatedWitnesses.false_check_refuses
#print axioms Zetesis.EvaluatedWitnesses.selected_iff
#print axioms Zetesis.EvaluatedWitnesses.original_witness_truth
#print axioms Zetesis.EvaluatedWitnesses.frozen_witness_truth
#print axioms Zetesis.EvaluatedWitnesses.complete_row_collection_keeps_stability
#print axioms Zetesis.EvaluationPrefix.write_prefix
#print axioms Zetesis.EvaluationPrefix.storage_preservation
#print axioms Zetesis.EvaluationPrefix.reset_preservation
#print axioms Zetesis.EvaluationPrefix.evaluate_append
#print axioms Zetesis.EvaluationPrefix.root_preservation
#print axioms Zetesis.insertAtom_grows
#print axioms Zetesis.insertAtom_contains
#print axioms Zetesis.insertAtom_duplicate
#print axioms Zetesis.insertAtom_idempotent
#print axioms Zetesis.applyEvents_grows
#print axioms Zetesis.applyEvents_append
#print axioms Zetesis.legalEvents_append
#print axioms Zetesis.applyEvents_prefix_grows
#print axioms Zetesis.insertAtom_sound
#print axioms Zetesis.legalEvents_sound
#print axioms Zetesis.events_from_bottom_sound
#print axioms Zetesis.completed_events_exact
#print axioms Zetesis.completed_events_order_independent
#print axioms Zetesis.duplicate_events_legal
#print axioms Zetesis.duplicate_events_same_state
#print axioms Zetesis.EventCounterexamples.factOperator_monotone
#print axioms Zetesis.EventCounterexamples.empty_trace_legal
#print axioms Zetesis.EventCounterexamples.empty_trace_not_closed
#print axioms Zetesis.EventCounterexamples.self_support_closed
#print axioms Zetesis.EventCounterexamples.self_support_least_empty
#print axioms Zetesis.EventCounterexamples.self_support_not_sound
#print axioms Zetesis.EventCounterexamples.self_support_has_no_complete_full_trace
#print axioms Zetesis.Examples.choice_consequence
#print axioms Zetesis.Examples.choice_gamma
#print axioms Zetesis.Examples.choice_empty_stable
#print axioms Zetesis.Examples.choice_full_stable
#print axioms Zetesis.Examples.choice_gamma_not_antimonotone
#print axioms Zetesis.Examples.fact_constraint_consequence
#print axioms Zetesis.Examples.fact_constraint_gamma
#print axioms Zetesis.Examples.fact_constraint_stable
#print axioms Zetesis.Examples.missing_constraint_gate_loses_model
#print axioms Zetesis.Examples.missing_constraint_gate_not_carrier
#print axioms Zetesis.Examples.Choices.candidate_closure
#print axioms Zetesis.Examples.Choices.candidate_answer_set
#print axioms Zetesis.ExtremumCandidates.choose_is_input
#print axioms Zetesis.ExtremumCandidates.extreme_none_iff
#print axioms Zetesis.ExtremumCandidates.extreme_some_mem
#print axioms Zetesis.ExtremumCandidates.complete_candidate_coverage
#print axioms Zetesis.ExtremumCandidates.empty_maximum_is_infimum
#print axioms Zetesis.ExtremumCandidates.empty_minimum_is_supremum
#print axioms Zetesis.ExtremumCandidates.finite_ne_infimum
#print axioms Zetesis.ExtremumCandidates.finite_ne_supremum
#print axioms Zetesis.ExtremumCandidates.candidate_length
#print axioms Zetesis.ExtremumHeadActivity.mem_values
#print axioms Zetesis.ExtremumHeadActivity.formula_original
#print axioms Zetesis.ExtremumHeadActivity.formula_frozen
#print axioms Zetesis.ExtremumHeadActivity.inactive_measure
#print axioms Zetesis.ExtremumHeadActivity.finite_measure_has_witness
#print axioms Zetesis.ExtremumHeadActivity.same_rows_preserve_measure
#print axioms Zetesis.ExtremumHeadActivity.bound_frozen
#print axioms Zetesis.ExtremumHeadActivity.stable_in_context
#print axioms Zetesis.ExtremumPresence.mandatory_dominance_excludes_numeric
#print axioms Zetesis.ExtremumPresence.optional_numeric_witness
#print axioms Zetesis.ExtremumPresence.possible_extension_retains_presence
#print axioms Zetesis.ExtremumPresence.numeric_presence_transport
#print axioms Zetesis.ExtremumPresence.mandatory_class_excludes_numeric_result
#print axioms Zetesis.Feedback.witness_exact
#print axioms Zetesis.Feedback.witness_theory_exact
#print axioms Zetesis.Feedback.allow_iff_no_countermodel
#print axioms Zetesis.Feedback.stable_allows
#print axioms Zetesis.Feedback.feedback_preserves_stability
#print axioms Zetesis.Feedback.countermodel_excludes_candidate
#print axioms Zetesis.Feedback.excluded_has_countermodel
#print axioms Zetesis.Feedback.stable_allows_all
#print axioms Zetesis.Feedback.all_feedback_preserves_stability
#print axioms Zetesis.Feedback.recorded_countermodel_excludes_candidate
#print axioms Zetesis.Feedback.unit_choice_reduct_models
#print axioms Zetesis.Feedback.unit_choice_empty_stable
#print axioms Zetesis.Feedback.unit_choice_full_stable
#print axioms Zetesis.Feedback.unit_choice_comparable_stable_models
#print axioms Zetesis.Feedback.unit_choice_not_classically_minimal
#print axioms Zetesis.Feedback.classical_minimal_stable_sub_equal
#print axioms Zetesis.Feedback.other_stable_outside_cones
#print axioms Zetesis.Feedback.cone_filter_exact
#print axioms Zetesis.Feedback.proper_subset_not_classical_model
#print axioms Zetesis.Feedback.proper_superset_not_stable
#print axioms Zetesis.Ferraris.reduct_self
#print axioms Zetesis.Ferraris.models_reduct_self
#print axioms Zetesis.Ferraris.stable_iff_minimal_reduct
#print axioms Zetesis.Ferraris.stable_append_of_models
#print axioms Zetesis.Ferraris.stable_append_facts
#print axioms Zetesis.Ferraris.atom_reduct
#print axioms Zetesis.Ferraris.neg_atom_reduct
#print axioms Zetesis.Ferraris.double_neg_atom_reduct
#print axioms Zetesis.Ferraris.choice_reduct_guard
#print axioms Zetesis.Ferraris.only_false_minimal
#print axioms Zetesis.Ferraris.only_true_minimal
#print axioms Zetesis.Ferraris.incomparable_minimal_models
#print axioms Zetesis.Ferraris.no_least_model
#print axioms Zetesis.Ferraris.example_is_full_reduct
#print axioms Zetesis.Ferraris.reduct_has_no_least_model
#print axioms Zetesis.Ferraris.double_neg_satisfies
#print axioms Zetesis.Ferraris.double_neg_reduct_eq_truth
#print axioms Zetesis.Ferraris.double_neg_formula_reduct
#print axioms Zetesis.Ferraris.models_cons
#print axioms Zetesis.Ferraris.models_reduct_cons_double_neg
#print axioms Zetesis.Ferraris.stable_cons_double_neg_iff
#print axioms Zetesis.Ferraris.stable_cons_double_neg_iff_of_satisfies
#print axioms Zetesis.Ferraris.stable_guard_theory_iff
#print axioms Zetesis.Ferraris.stable_guard_theory_iff_of_stable_entails
#print axioms Zetesis.Ferraris.masked_eval_iff_reduct
#print axioms Zetesis.Ferraris.masked_models_iff_reduct
#print axioms Zetesis.Ferraris.stable_iff_masked_minimality
#print axioms Zetesis.FiniteBindings.strict_endpoints
#print axioms Zetesis.FiniteBindings.tighten_membership
#print axioms Zetesis.FiniteBindings.compiled_membership
#print axioms Zetesis.FiniteBindings.candidate_membership
#print axioms Zetesis.FiniteBindings.candidate_specification
#print axioms Zetesis.FiniteBindings.formula_membership
#print axioms Zetesis.FiniteBindings.original_in_context
#print axioms Zetesis.FiniteBindings.frozen_in_context
#print axioms Zetesis.FiniteBindings.stable_in_context
#print axioms Zetesis.FinitePools.product_complete
#print axioms Zetesis.FinitePools.empty_occurrence
#print axioms Zetesis.FinitePools.duplicate_alternative
#print axioms Zetesis.FinitePools.independent_equal_occurrences
#print axioms Zetesis.FinitePools.original_in_context
#print axioms Zetesis.FinitePools.frozen_in_context
#print axioms Zetesis.FinitePools.stable_in_context
#print axioms Zetesis.FinitePools.flattening_changes_original_truth
#print axioms Zetesis.FiniteValues.input_agreement
#print axioms Zetesis.FiniteValues.extension_target
#print axioms Zetesis.FiniteValues.extension_preserves
#print axioms Zetesis.FiniteValues.constructor_identity
#print axioms Zetesis.FiniteValues.tuple_identity
#print axioms Zetesis.FiniteValues.original_literal_identity
#print axioms Zetesis.FiniteValues.frozen_literal_identity
#print axioms Zetesis.FiniteValues.failed_step
#print axioms Zetesis.GatePositions.atoms_exact
#print axioms Zetesis.GatePositions.retained_position_exact
#print axioms Zetesis.GateProjection.bitwise_support_exact
#print axioms Zetesis.GateProjection.bitwise_support_bounded
#print axioms Zetesis.GateProjection.aliased_intersection_exact
#print axioms Zetesis.GateRestrictions.fact_in_model
#print axioms Zetesis.GateRestrictions.answer_set_avoids
#print axioms Zetesis.GateRestrictions.upward_rejection
#print axioms Zetesis.GateRestrictions.suffix_region_rejected
#print axioms Zetesis.GroundGuards.constant_original
#print axioms Zetesis.GroundGuards.constant_frozen
#print axioms Zetesis.GroundGuards.guard_original
#print axioms Zetesis.GroundGuards.guard_frozen
#print axioms Zetesis.GroundGuards.evaluated_guard_equivalent
#print axioms Zetesis.GroundGuards.chain_evaluation
#print axioms Zetesis.GroundGuards.negative_chain_scope
#print axioms Zetesis.GroundGuards.double_negative_chain_scope
#print axioms Zetesis.GroundGuards.negating_each_comparison_is_different
#print axioms Zetesis.GroundGuards.replacement_in_formula_context
#print axioms Zetesis.GroundGuards.replacement_preserves_stability
#print axioms Zetesis.GroundGuards.classical_tautology_is_not_a_guard_replacement
#print axioms Zetesis.HeadContributions.neutral_values_are_zero
#print axioms Zetesis.HeadContributions.nonpositive_is_neutral
#print axioms Zetesis.HeadContributions.positive_measure
#print axioms Zetesis.HeadContributions.unbounded_equivalent
#print axioms Zetesis.HeadContributions.unbounded_in_context
#print axioms Zetesis.HeadContributions.neutral_permission_is_not_truth
#print axioms Zetesis.HeadContributions.missing_extremum_is_neutral
#print axioms Zetesis.HeadContributions.complete_extremum_conservative
#print axioms Zetesis.HeadContributions.only_missing_extremum
#print axioms Zetesis.HeadContributions.selected_extremum_values
#print axioms Zetesis.HeadContributions.extremum_formula_original
#print axioms Zetesis.HeadContributions.extremum_bound_frozen
#print axioms Zetesis.HeadContributions.extremum_head_in_context
#print axioms Zetesis.HeadMeasures.bound_original
#print axioms Zetesis.HeadMeasures.bound_frozen
#print axioms Zetesis.HeadMeasures.bound_equivalent
#print axioms Zetesis.HeadMeasures.permission_equivalent
#print axioms Zetesis.HeadMeasures.group_equivalent
#print axioms Zetesis.HeadMeasures.stable_in_context
#print axioms Zetesis.IndexedCandidates.lookup_empty
#print axioms Zetesis.IndexedCandidates.lookup_insert
#print axioms Zetesis.IndexedCandidates.lookup_index
#print axioms Zetesis.IndexedCandidates.block_exact
#print axioms Zetesis.IndexedCandidates.index_equals_all_blocks
#print axioms Zetesis.IndexedCandidates.identical_projection_same_filter
#print axioms Zetesis.IndexedCandidates.recorded_projection_rejected
#print axioms Zetesis.IndexedCandidates.unseen_projection_allowed
#print axioms Zetesis.IndexedCandidates.failed_literal_forced
#print axioms Zetesis.IndexedCandidates.failed_literal_query_exact
#print axioms Zetesis.IndexedCandidates.frozen_countermodel_probe_exact
#print axioms Zetesis.IntegerEnvelopes.path_bound
#print axioms Zetesis.IntegerEnvelopes.anchored_envelope
#print axioms Zetesis.IntegerEnvelopes.addition_envelope
#print axioms Zetesis.IntegerEnvelopes.negation_envelope
#print axioms Zetesis.IntegerEnvelopes.product_lower_bound
#print axioms Zetesis.IntegerEnvelopes.sum_lower_bound
#print axioms Zetesis.IntegerEnvelopes.positive_endpoint
#print axioms Zetesis.IntegerEnvelopes.negative_endpoint
#print axioms Zetesis.IntegerEnvelopes.affine_envelope
#print axioms Zetesis.IntegerEnvelopes.integer_membership
#print axioms Zetesis.IntegerEnvelopes.filtered_bindings_exact
#print axioms Zetesis.finiteIter_stage_mono
#print axioms Zetesis.finiteList_uniform_stage
#print axioms Zetesis.finiteList_uniform_stage_if
#print axioms Zetesis.Semantics.omegaIter_consequence_closed
#print axioms Zetesis.Semantics.gamma_iff_finiteIter
#print axioms Zetesis.Semantics.gamma_eq_omegaIter
#print axioms Zetesis.Semantics.finite_convergence_of_cover
#print axioms Zetesis.Semantics.gamma_covered_by_programHeads
#print axioms Zetesis.Semantics.finite_normalized_program_converges
#print axioms Zetesis.JoinFrames.reset_root_exact
#print axioms Zetesis.JoinFrames.child_overwrite_exact
#print axioms Zetesis.JoinFrames.completed_walk_exact
#print axioms Zetesis.JoinFrames.prepared_prefix_exact
#print axioms Zetesis.JoinFrames.retained_frames_irrelevant
#print axioms Zetesis.JoinFrames.stale_root_can_erase_current_truth
#print axioms Zetesis.LazyRounds.world_below_union
#print axioms Zetesis.LazyRounds.union_scan_covers_world
#print axioms Zetesis.LazyRounds.world_consequences_exact
#print axioms Zetesis.LazyRounds.world_constraints_exact
#print axioms Zetesis.LazyRounds.chunk_concatenation
#print axioms Zetesis.LazyRounds.completed_round_closed
#print axioms Zetesis.LazyRounds.completed_round_exact
#print axioms Zetesis.Lifted.composition_exact
#print axioms Zetesis.Lifted.bind_monotone
#print axioms Zetesis.Lifted.ruleTransform_monotone
#print axioms Zetesis.Lifted.filter_gate_commute
#print axioms Zetesis.Lifted.gate_pushdown_exact
#print axioms Zetesis.Lifted.necessary_gate_pushdown_exact
#print axioms Zetesis.Lifted.materialized_sound
#print axioms Zetesis.Lifted.materialized_complete
#print axioms Zetesis.Lifted.materialized_exact
#print axioms Zetesis.Lifted.omissions_cover
#print axioms Zetesis.Lifted.certified_materializer_exact
#print axioms Zetesis.Lifted.materialized_selection_monotone
#print axioms Zetesis.Lifted.materialized_replay_idempotent
#print axioms Zetesis.Lifted.materialized_constraint_exact
#print axioms Zetesis.Lifted.family_exact
#print axioms Zetesis.Lifted.family_closedness_exact
#print axioms Zetesis.Lifted.lazy_step_exact
#print axioms Zetesis.Lifted.lazy_stages_exact
#print axioms Zetesis.Lifted.empty_snapshot_covered
#print axioms Zetesis.Lifted.grown_snapshot_not_covered
#print axioms Zetesis.Lifted.omitted_new_consequence
#print axioms Zetesis.LiftedBridge.family_consequence_ground
#print axioms Zetesis.LiftedBridge.family_constraints_ground
#print axioms Zetesis.LiftedBridge.lifted_gamma_ground
#print axioms Zetesis.LiftedBridge.lazy_gamma_ground
#print axioms Zetesis.LiftedBridge.lazy_stage_sound
#print axioms Zetesis.LiftedBridge.completed_lazy_stage_exact
#print axioms Zetesis.LiftedBridge.completed_lazy_stage_accept_sound
#print axioms Zetesis.LiftedBridge.lazy_accept_sound
#print axioms Zetesis.NegativeEligibility.negative_activity_frozen
#print axioms Zetesis.NegativeEligibility.double_negative_activity_frozen
#print axioms Zetesis.NegativeEligibility.double_negative_gate_is_not_positive
#print axioms Zetesis.NegativeHeads.negative_literal_reduct
#print axioms Zetesis.NegativeHeads.double_negative_literal_reduct
#print axioms Zetesis.NegativeHeads.head_reduct_of_positive_kept
#print axioms Zetesis.NegativeHeads.reduct_truth_requires_original
#print axioms Zetesis.NegativeHeads.stable_has_positive_producer
#print axioms Zetesis.NegativeHeads.support_formula_truth
#print axioms Zetesis.NegativeHeads.stable_satisfies_support
#print axioms Zetesis.NegativeHeads.guarded_theory_preserves_stable_models
#print axioms Zetesis.NormalFerraris.satisfies_fold
#print axioms Zetesis.NormalFerraris.reduct_fold
#print axioms Zetesis.NormalFerraris.satisfies_conjunction
#print axioms Zetesis.NormalFerraris.reduct_conjunction
#print axioms Zetesis.NormalFerraris.satisfies_antecedent
#print axioms Zetesis.NormalFerraris.reduct_antecedent
#print axioms Zetesis.NormalFerraris.satisfies_head
#print axioms Zetesis.NormalFerraris.reduct_head
#print axioms Zetesis.NormalFerraris.satisfies_rule
#print axioms Zetesis.NormalFerraris.reduct_rule
#print axioms Zetesis.NormalFerraris.reduct_model_iff_rules
#print axioms Zetesis.NormalFerraris.mem_translate
#print axioms Zetesis.NormalFerraris.false_filter_omitted
#print axioms Zetesis.NormalFerraris.translate_applicable
#print axioms Zetesis.NormalFerraris.models_translate
#print axioms Zetesis.NormalFerraris.models_frozen_translate
#print axioms Zetesis.NormalFerraris.frozen_subset_model_iff
#print axioms Zetesis.NormalFerraris.answer_set_iff
#print axioms Zetesis.NormalFerraris.applicable_answer_set_iff
#print axioms Zetesis.NormalFerraris.applicable_frozen_subset_model_iff
#print axioms Zetesis.NormalFerraris.ferraris_answer_set_iff_closure
#print axioms Zetesis.ObjectiveBounds.mem_prune
#print axioms Zetesis.ObjectiveBounds.incumbent_survives
#print axioms Zetesis.ObjectiveBounds.tighten
#print axioms Zetesis.ObjectiveBounds.optimum_survives
#print axioms Zetesis.ObjectiveBounds.excluded_is_worse
#print axioms Zetesis.ObjectiveBounds.bounded_best_is_global
#print axioms Zetesis.ObjectiveBounds.bounded_ties_exact
#print axioms Zetesis.ObjectiveBounds.bounded_optimum_keeps_original_reduct
#print axioms Zetesis.ObjectiveConditionTable.node_correspondence
#print axioms Zetesis.ObjectiveConditionTable.rows_correspondence
#print axioms Zetesis.ObjectiveConditionTable.backward_node_total
#print axioms Zetesis.ObjectiveConditionTable.admitted_rows_total
#print axioms Zetesis.ObjectiveConditionTable.unfolding_correspondence
#print axioms Zetesis.ObjectiveConditionTable.admitted_correspondence
#print axioms Zetesis.ObjectiveConditionTable.original_truth
#print axioms Zetesis.ObjectiveConditionTable.model_identity
#print axioms Zetesis.ObjectiveConditions.original_truth
#print axioms Zetesis.ObjectiveConditions.formula_query_truth
#print axioms Zetesis.ObjectiveConditions.formula_query_changes_reduct
#print axioms Zetesis.ObjectiveConditions.model_identity
#print axioms Zetesis.ObjectiveConditions.condition_vector
#print axioms Zetesis.ObjectiveDirections.same_contribution_iff_key
#print axioms Zetesis.ObjectiveDirections.raw_cost_keys
#print axioms Zetesis.ObjectiveDirections.conditions_for_active
#print axioms Zetesis.ObjectiveDirections.normalized_keys_unique
#print axioms Zetesis.ObjectiveDirections.enabled_key_iff
#print axioms Zetesis.ObjectiveDirections.weighted_filter
#print axioms Zetesis.ObjectiveDirections.weighted_map
#print axioms Zetesis.ObjectiveDirections.compiled_cost_enabled
#print axioms Zetesis.ObjectiveDirections.normalization_preserves_cost
#print axioms Zetesis.ObjectiveDirections.normalization_preserves_vector
#print axioms Zetesis.ObjectiveDirections.normalization_preserves_comparison
#print axioms Zetesis.ObjectiveDirections.normalization_preserves_optimal_models
#print axioms Zetesis.ObjectiveDirections.normalized_optimum_retains_reduct
#print axioms Zetesis.ObjectiveDirections.normalization_preserves_tie_list
#print axioms Zetesis.ObjectiveDirections.opposite_directions_coalesce
#print axioms Zetesis.ObjectiveDirections.same_weight_directions_distinct
#print axioms Zetesis.ObjectiveDirections.collision_and_cancellation_examples
#print axioms Zetesis.ObjectiveEligibility.possible_support_covers
#print axioms Zetesis.ObjectiveEligibility.negation_covers
#print axioms Zetesis.ObjectiveEligibility.conjunction_covers
#print axioms Zetesis.ObjectiveEligibility.disjunction_covers
#print axioms Zetesis.ObjectiveEligibility.optional_contradiction
#print axioms Zetesis.ObjectiveEligibility.absent_excludes
#print axioms Zetesis.ObjectivePriorities.selected_presence
#print axioms Zetesis.ObjectivePriorities.completed_presence
#print axioms Zetesis.ObjectivePriorities.ignored_priority_preserves_vector
#print axioms Zetesis.ObjectivePriorities.independent_fields_invent_priority
#print axioms Zetesis.ObjectivePriorities.raw_partition_cost
#print axioms Zetesis.ObjectivePriorities.partition_cost
#print axioms Zetesis.ObjectivePriorities.partition_vector
#print axioms Zetesis.ObjectivePriorities.partition_optima
#print axioms Zetesis.ObjectivePriorities.zero_slot_comparison
#print axioms Zetesis.ObjectivePriorities.zero_slot_optima
#print axioms Zetesis.ObjectiveTransport.present_transport
#print axioms Zetesis.ObjectiveTransport.transport_key
#print axioms Zetesis.ObjectiveTransport.transport_composes
#print axioms Zetesis.ObjectiveTransport.active_keys_transport
#print axioms Zetesis.ObjectiveTransport.mixed_cost_transport
#print axioms Zetesis.ObjectiveTransport.cost_vector_transport
#print axioms Zetesis.ObjectiveValues.ignored_entry_has_no_numeric_key
#print axioms Zetesis.ObjectiveValues.numeric_entries_ignore
#print axioms Zetesis.ObjectiveValues.ignored_entry_preserves_presence
#print axioms Zetesis.ObjectiveValues.zero_entry_retains_presence
#print axioms Zetesis.ObjectiveValues.selected_entry_preserves_key
#print axioms Zetesis.ObjectiveValues.ignored_entry_preserves_cost
#print axioms Zetesis.ObjectiveValues.ignored_entry_preserves_optima
#print axioms Zetesis.Observations.completed_terms_exact
#print axioms Zetesis.Observations.same_rows_preserve_terms
#print axioms Zetesis.Observations.shared_equality_choice_exact
#print axioms Zetesis.Observations.equal_measures_do_not_identify_tuple_keys
#print axioms Zetesis.Observations.original_family_projection
#print axioms Zetesis.Observations.decorated_world_view
#print axioms Zetesis.Observations.different_models_remain_different_records
#print axioms Zetesis.Observations.display_deduplication_can_shrink_a_family
#print axioms Zetesis.Optimization.best_none_iff
#print axioms Zetesis.Optimization.best_spec
#print axioms Zetesis.Optimization.optimal_is_stable
#print axioms Zetesis.Optimization.optimal_is_minimal_reduct
#print axioms Zetesis.Optimization.completed_best_is_optimal
#print axioms Zetesis.Optimization.completed_ties_exact
#print axioms Zetesis.Optimization.constant_on_stable_iff
#print axioms Zetesis.OptionalIndex.successor_fits
#print axioms Zetesis.OptionalIndex.decode_encode
#print axioms Zetesis.OptionalIndex.encode_decode
#print axioms Zetesis.OptionalIndex.encode_injective
#print axioms Zetesis.OptionalIndex.optional_round_trip
#print axioms Zetesis.OptionalIndex.absence_exact
#print axioms Zetesis.OptionalIndex.replacement_commutes
#print axioms Zetesis.OrderedBounds.separated_comparison
#print axioms Zetesis.OrderedBounds.constant_aggregate
#print axioms Zetesis.OrderedBounds.separated_aggregate
#print axioms Zetesis.OrderedBounds.replacement_in_context
#print axioms Zetesis.OrderedBounds.measured_head_in_context
#print axioms Zetesis.OrderedHeadActivity.mem_values
#print axioms Zetesis.OrderedHeadActivity.frozen_selection
#print axioms Zetesis.OrderedHeadActivity.selected_values
#print axioms Zetesis.OrderedHeadActivity.formula_original
#print axioms Zetesis.OrderedHeadActivity.formula_frozen
#print axioms Zetesis.OrderedHeadActivity.measure_predicate
#print axioms Zetesis.OrderedHeadActivity.bound_frozen
#print axioms Zetesis.OrderedProbes.boundary_partitions
#print axioms Zetesis.OrderedProbes.complete_match_retained
#print axioms Zetesis.Outcomes.completed_unsatisfiable_iff_empty
#print axioms Zetesis.Outcomes.delivered_values_are_valid
#print axioms Zetesis.Outcomes.empty_delivery_can_hide_a_valid_model
#print axioms Zetesis.OuterNegativeConsumers.negative_body_frozen
#print axioms Zetesis.OuterNegativeConsumers.double_negative_body_frozen
#print axioms Zetesis.OuterNegativeConsumers.negative_projection_frozen
#print axioms Zetesis.OuterNegativeConsumers.double_negative_projection_frozen
#print axioms Zetesis.OuterRanges.row_membership
#print axioms Zetesis.OuterRanges.covered_range
#print axioms Zetesis.OuterRanges.appended_frames
#print axioms Zetesis.OuterRanges.original_rows
#print axioms Zetesis.OuterRanges.frozen_rows
#print axioms Zetesis.PackedQueryLiterals.decode_encode
#print axioms Zetesis.PackedQueryLiterals.encode_injective
#print axioms Zetesis.PackedQueryLiterals.encode_lt
#print axioms Zetesis.PackedQueryLiterals.packed_truth
#print axioms Zetesis.PartitionCapacities.count_append
#print axioms Zetesis.PartitionCapacities.count_members
#print axioms Zetesis.PartitionCapacities.capacity_bounds
#print axioms Zetesis.PartitionCapacities.local_lower
#print axioms Zetesis.PartitionCapacities.inconsistent_premises
#print axioms Zetesis.PartitionCapacities.full_capacity
#print axioms Zetesis.PositiveArguments.declared_input_agreement
#print axioms Zetesis.PositiveArguments.successful_check
#print axioms Zetesis.PositiveArguments.undefined_check
#print axioms Zetesis.PositiveArguments.empty_plan
#print axioms Zetesis.PositiveArguments.selected_iff
#print axioms Zetesis.PositiveArguments.selected_atom_has_support
#print axioms Zetesis.PositiveArguments.repeated_selection
#print axioms Zetesis.PositiveArguments.original_atom_preserved
#print axioms Zetesis.PositiveArguments.frozen_atom_preserved
#print axioms Zetesis.ProjectedConditionals.complete_projection
#print axioms Zetesis.ProjectedConditionals.original_semantics
#print axioms Zetesis.ProjectedConditionals.frozen_semantics
#print axioms Zetesis.ProjectedConditionals.negative_frozen
#print axioms Zetesis.ProjectedConditionals.double_negative_frozen
#print axioms Zetesis.ProjectedConditionals.empty_carriers_differ
#print axioms Zetesis.ProjectedConditionals.omitted_witness_changes_negation
#print axioms Zetesis.Propagation.narrow_decreases
#print axioms Zetesis.Propagation.narrow_retains_completion
#print axioms Zetesis.Propagation.narrow_models_iff
#print axioms Zetesis.Propagation.narrow_monotone
#print axioms Zetesis.Propagation.sweep_decreases
#print axioms Zetesis.Propagation.sweep_retains_completion
#print axioms Zetesis.Propagation.sweep_models_iff
#print axioms Zetesis.Propagation.finite_sweeps_models_iff
#print axioms Zetesis.Propagation.empty_domain_refutes
#print axioms Zetesis.Propagation.parallel_round_models_iff
#print axioms Zetesis.Propagation.stale_projection_retains_completion
#print axioms Zetesis.Propagation.enabled_gate_full_equivalence
#print axioms Zetesis.Propagation.disabled_gate_leaves_inputs_free
#print axioms Zetesis.Propagation.disabled_implication_must_not_be_enforced
#print axioms Zetesis.Propagation.gate_rows_exact
#print axioms Zetesis.Propagation.gate_constraint_exact
#print axioms Zetesis.Propagation.full_and_equivalence_propagates_backwards
#print axioms Zetesis.Propagation.subset_domains_exact
#print axioms Zetesis.Propagation.strict_drop_exact
#print axioms Zetesis.Propagation.proper_subset_domains_exact
#print axioms Zetesis.Propagation.empty_candidate_has_no_proper_tested_world
#print axioms Zetesis.Propagation.inner_query_exact
#print axioms Zetesis.Propagation.propagated_conflict_establishes_stability
#print axioms Zetesis.Propagation.propagated_conflict_with_auxiliaries
#print axioms Zetesis.Propagation.parity_projection_is_quiescent
#print axioms Zetesis.Propagation.quiescent_unknown_can_be_unsatisfiable
#print axioms Zetesis.Propagation.unsupported_self_implication_is_not_stable
#print axioms Zetesis.QueryCompaction.literal_negated_eval
#print axioms Zetesis.QueryCompaction.wire_negated_eval
#print axioms Zetesis.QueryCompaction.compact_gate_eval
#print axioms Zetesis.QueryCompaction.and_clauses_exact
#print axioms Zetesis.QueryCompaction.or_clauses_exact
#print axioms Zetesis.QueryCompaction.gate_clauses_exact
#print axioms Zetesis.QueryCompaction.gate_clauses_unique_extension
#print axioms Zetesis.QueryCompaction.canonical_and_gate_exact
#print axioms Zetesis.QueryCompaction.and_clauses_commute
#print axioms Zetesis.QueryCompaction.repeated_and_outputs_equal
#print axioms Zetesis.QueryCompaction.compacted_gate_encoding_exact
#print axioms Zetesis.QueryCompaction.plan_query_eval
#print axioms Zetesis.QueryCompaction.smart_gate_eval
#print axioms Zetesis.QueryCompaction.smart_negated_eval
#print axioms Zetesis.QueryCompaction.compact_eval
#print axioms Zetesis.QueryCompaction.boolean_implication_iff
#print axioms Zetesis.QueryCompaction.formula_truth_iff
#print axioms Zetesis.QueryCompaction.masked_query_eval_iff
#print axioms Zetesis.QueryCompaction.reduct_query_eval_iff
#print axioms Zetesis.QueryCompaction.query_models_iff_reduct
#print axioms Zetesis.QueryCompaction.exists_boolean_representation
#print axioms Zetesis.QueryCompaction.compacted_countermodels_iff
#print axioms Zetesis.QueryCompaction.stable_iff_compacted_queries
#print axioms Zetesis.QueryCompaction.assignment_branch_partition
#print axioms Zetesis.QueryCompaction.assignment_branches_disjoint
#print axioms Zetesis.QueryCompaction.exhausted_branches_refute
#print axioms Zetesis.RelationExtension.reconstruction_preserved
#print axioms Zetesis.RelationExtension.acceptance_preserved
#print axioms Zetesis.RuleFactorization.false_reduct
#print axioms Zetesis.RuleFactorization.reduct_conj
#print axioms Zetesis.RuleFactorization.reduct_disj
#print axioms Zetesis.RuleFactorization.reduct_imp
#print axioms Zetesis.RuleFactorization.satisfies_any
#print axioms Zetesis.RuleFactorization.reduct_any
#print axioms Zetesis.RuleFactorization.models_pairs
#print axioms Zetesis.RuleFactorization.original_factorization
#print axioms Zetesis.RuleFactorization.reduct_models_pairs
#print axioms Zetesis.RuleFactorization.frozen_factorization
#print axioms Zetesis.RuleFactorization.models_append
#print axioms Zetesis.RuleFactorization.original_in_context
#print axioms Zetesis.RuleFactorization.frozen_in_context
#print axioms Zetesis.RuleFactorization.stable_in_context
#print axioms Zetesis.ScalarArithmetic.checked_success
#print axioms Zetesis.ScalarArithmetic.checked_overflow
#print axioms Zetesis.ScalarArithmetic.zero_divisor
#print axioms Zetesis.ScalarArithmetic.exceptional_quotient
#print axioms Zetesis.ScalarArithmetic.division_success
#print axioms Zetesis.ScalarArithmetic.negative_exponent
#print axioms Zetesis.ScalarArithmetic.power_success
#print axioms Zetesis.ScalarArithmetic.operation_agreement
#print axioms Zetesis.ScalarArithmetic.first_failure
#print axioms Zetesis.ScalarArithmetic.successful_step
#print axioms Zetesis.Cube.contains_singleton
#print axioms Zetesis.Cube.contains_splitFalse
#print axioms Zetesis.Cube.contains_splitTrue
#print axioms Zetesis.Cube.split_partition
#print axioms Zetesis.Cube.split_disjoint
#print axioms Zetesis.Cube.fresh_branches
#print axioms Zetesis.Cube.contains_narrow
#print axioms Zetesis.Cube.narrow_preserves_valid
#print axioms Zetesis.Cube.consequence_narrow_preserves
#print axioms Zetesis.CoverageTree.mem_outputs_iff
#print axioms Zetesis.CoverageTree.outputs_sound
#print axioms Zetesis.CoverageTree.outputs_complete
#print axioms Zetesis.CoverageTree.outputs_nodup
#print axioms Zetesis.CoverageTree.exhausted_no_valid
#print axioms Zetesis.rejected_sample_does_not_refute_region
#print axioms Zetesis.accepted_sample_does_not_exhaust_region
#print axioms Zetesis.SeedSelections.materialization_exact
#print axioms Zetesis.Semantics.body_mono
#print axioms Zetesis.Semantics.consequence_mono
#print axioms Zetesis.Semantics.constraints_down
#print axioms Zetesis.Semantics.gamma_closed
#print axioms Zetesis.Semantics.gamma_le
#print axioms Zetesis.Semantics.stable_iff_gamma
#print axioms Zetesis.Semantics.gate_eq_on
#print axioms Zetesis.Semantics.consequence_eq_on
#print axioms Zetesis.Semantics.gamma_eq_on
#print axioms Zetesis.Semantics.constraints_eq_on
#print axioms Zetesis.Semantics.accepted_seed_in_carrier
#print axioms Zetesis.Semantics.accept_sound
#print axioms Zetesis.Semantics.stable_complete
#print axioms Zetesis.Semantics.accepted_seed_unique
#print axioms Zetesis.Semantics.stable_iff_exists_seed
#print axioms Zetesis.SignedHeadElements.operand_original
#print axioms Zetesis.SignedHeadElements.operand_frozen
#print axioms Zetesis.SignedHeadElements.double_negative_differs_from_positive
#print axioms Zetesis.SignedHeadElements.atomic_witness_key
#print axioms Zetesis.SignedHeadElements.atomic_sign_keys_distinct
#print axioms Zetesis.SignedHeadElements.boolean_witness_key
#print axioms Zetesis.SignedHeadElements.boolean_occurrence_keys_distinct
#print axioms Zetesis.SignedHeadElements.activity_original
#print axioms Zetesis.SignedHeadElements.activity_frozen
#print axioms Zetesis.SignedHeadElements.permission_original
#print axioms Zetesis.SignedHeadElements.signed_permission_frozen
#print axioms Zetesis.SignedHeadElements.row_activity_equivalent
#print axioms Zetesis.SignedHeadElements.activity_equivalent
#print axioms Zetesis.SignedHeadElements.permission_equivalent
#print axioms Zetesis.SignedHeadElements.unsigned_atom_rows
#print axioms Zetesis.SignedHeadElements.formula_equivalent
#print axioms Zetesis.SignedHeadElements.group_equivalent
#print axioms Zetesis.SignedHeadElements.group_in_context
#print axioms Zetesis.SignedHeadElements.coalesced_group_in_context
#print axioms Zetesis.SignedHeadElements.nonproducing_group_in_context
#print axioms Zetesis.SignedObjectiveBounds.magnitude_nonnegative
#print axioms Zetesis.SignedObjectiveBounds.contribution_exact
#print axioms Zetesis.SignedObjectiveBounds.nonnegative_cost_nonnegative
#print axioms Zetesis.SignedObjectiveBounds.compiled_cost_exact
#print axioms Zetesis.SignedObjectiveBounds.mixed_cost_exact
#print axioms Zetesis.SignedObjectiveBounds.shifted_lt
#print axioms Zetesis.SignedObjectiveBounds.shifted_eq
#print axioms Zetesis.SignedObjectiveBounds.shifted_le
#print axioms Zetesis.SignedObjectiveBounds.shifted_vector_comparison
#print axioms Zetesis.SignedObjectiveBounds.normalization_preserves_comparison
#print axioms Zetesis.SignedObjectiveBounds.normalization_preserves_vector_equality
#print axioms Zetesis.SignedObjectiveBounds.candidate_filter_exact
#print axioms Zetesis.SignedObjectiveBounds.normalization_preserves_optimal_models
#print axioms Zetesis.SignedObjectiveBounds.normalization_preserves_tie_list
#print axioms Zetesis.SignedObjectiveBounds.optimal_survives_incumbent
#print axioms Zetesis.SignedObjectiveBounds.completed_scalar_ties_exact
#print axioms Zetesis.SignedObjectiveBounds.coalescing_order_example
#print axioms Zetesis.SingletonHeads.singleton_head_truth
#print axioms Zetesis.SingletonHeads.singleton_head_reduct
#print axioms Zetesis.SingletonHeads.singleton_rule_truth
#print axioms Zetesis.SingletonHeads.singleton_rule_reduct
#print axioms Zetesis.SingletonHeads.negative_singleton_reduct
#print axioms Zetesis.SingletonHeads.double_negative_singleton_reduct
#print axioms Zetesis.SingletonHeads.negative_singleton_has_no_producer
#print axioms Zetesis.SingletonHeads.double_negative_singleton_has_no_producer
#print axioms Zetesis.SourceContributions.chain_unique
#print axioms Zetesis.SourceContributions.chain_preserved
#print axioms Zetesis.SourceContributions.contributions_append
#print axioms Zetesis.SourceContributions.record_same
#print axioms Zetesis.SourceContributions.record_other
#print axioms Zetesis.SourceMeasures.selection_iff_sublist
#print axioms Zetesis.SourceMeasures.carrier_membership
#print axioms Zetesis.SourceMeasures.actual_value_covered
#print axioms Zetesis.SourceMeasures.invariant_carrier
#print axioms Zetesis.SourceMeasures.possible_extension
#print axioms Zetesis.SourceMeasures.source_priority_presence
#print axioms Zetesis.SourceSupport.unchanged_round_closed
#print axioms Zetesis.SourceSupport.stages_inside_closed
#print axioms Zetesis.SourceSupport.stable_inside_closed
#print axioms Zetesis.SourceSupport.completed_activity_covers
#print axioms Zetesis.StrongNegation.satisfies_rename
#print axioms Zetesis.StrongNegation.reduct_rename
#print axioms Zetesis.StrongNegation.frozen_rename
#print axioms Zetesis.StrongNegation.models_rename
#print axioms Zetesis.StrongNegation.frozen_theory_rename
#print axioms Zetesis.StrongNegation.pull_push
#print axioms Zetesis.StrongNegation.push_monotone
#print axioms Zetesis.StrongNegation.pull_monotone
#print axioms Zetesis.StrongNegation.image_sub
#print axioms Zetesis.StrongNegation.subset_image
#print axioms Zetesis.StrongNegation.stable_push
#print axioms Zetesis.StrongNegation.stable_target_is_image
#print axioms Zetesis.StrongNegation.stable_target_iff
#print axioms Zetesis.StrongNegation.polarity_distinct
#print axioms Zetesis.StrongNegation.encoded_polarity_distinct
#print axioms Zetesis.StrongNegation.coherent_on_of_coherent
#print axioms Zetesis.StrongNegation.coherent_iff_on_covered
#print axioms Zetesis.StrongNegation.coherence_classical
#print axioms Zetesis.StrongNegation.coherence_frozen
#print axioms Zetesis.StrongNegation.coherence_stable_filter
#print axioms Zetesis.StrongNegation.compiled_classical
#print axioms Zetesis.StrongNegation.compiled_frozen
#print axioms Zetesis.StrongNegation.compiled_stable
#print axioms Zetesis.StrongNegation.compiled_target_stable
#print axioms Zetesis.StrongNegation.compiled_rejects_incoherent_candidate
#print axioms Zetesis.StrongNegation.pair_covered_of_covered
#print axioms Zetesis.StrongNegation.pair_coverage_from_upper
#print axioms Zetesis.StrongNegation.coherent_iff_on_pair_covered
#print axioms Zetesis.StrongNegation.compiled_stable_of_pair_coverage
#print axioms Zetesis.StrongNegation.compiled_target_coherent_stable
#print axioms Zetesis.StrongNegation.compiled_push_classical
#print axioms Zetesis.StrongNegation.compiled_push_frozen
#print axioms Zetesis.StrongNegation.rename_default_negative
#print axioms Zetesis.StrongNegation.default_negative_frozen
#print axioms Zetesis.StrongNegation.signed_choice_frozen
#print axioms Zetesis.StrongNegation.bounded_group_frozen
#print axioms Zetesis.StrongNegation.bounded_group_stable_in_context
#print axioms Zetesis.StrongNegation.strong_is_not_default
#print axioms Zetesis.StrongNegation.conflicting_facts_are_unsatisfiable
#print axioms Zetesis.StrongNegation.negative_fact_stable
#print axioms Zetesis.StrongNegation.omitted_registry_admits_incoherence
#print axioms Zetesis.StrongNegation.independent_polarity_choices
#print axioms Zetesis.StructuralBindings.extends_refl
#print axioms Zetesis.StructuralBindings.extends_trans
#print axioms Zetesis.StructuralBindings.bind_sound
#print axioms Zetesis.StructuralBindings.matching_sound
#print axioms Zetesis.StructuralBindings.bind_fits
#print axioms Zetesis.StructuralBindings.matching_complete
#print axioms Zetesis.StructuralBindings.repeated_name_agreement
#print axioms Zetesis.StructuralBindings.failure_rolls_back
#print axioms Zetesis.StructuralBindings.wildcard_only_preserves_binding
#print axioms Zetesis.StructuralBindings.incompatible_shape_refuses
#print axioms Zetesis.StructuralBindings.matching_iff_consistent
#print axioms Zetesis.StructuralBindings.selected_row_coverage
#print axioms Zetesis.StructuralBindings.retained_atom_context
#print axioms Zetesis.StructuralBindings.retained_atom_stability
#print axioms Zetesis.StructuredWitnesses.original_witness_truth
#print axioms Zetesis.StructuredWitnesses.frozen_witness_truth
#print axioms Zetesis.StructuredWitnesses.completed_condition_preserved
#print axioms Zetesis.StructuredWitnesses.refused_witness_preserves_condition
#print axioms Zetesis.StructuredWitnesses.active_condition_requires_witness
#print axioms Zetesis.StructuredWitnesses.complete_row_collection_keeps_stability
#print axioms Zetesis.TernaryWatch.remaining_unique
#print axioms Zetesis.TernaryWatch.replacement_exact
#print axioms Zetesis.Thresholds.threshold_query_exact
#print axioms Zetesis.Thresholds.threshold_bound_antitone
#print axioms Zetesis.Thresholds.threshold_sum_monotone
#print axioms Zetesis.TightEvaluation.formula_value_true
#print axioms Zetesis.TightEvaluation.node_value_decode
#print axioms Zetesis.TightEvaluation.values_correspond
#print axioms Zetesis.TightEvaluation.value_at
#print axioms Zetesis.TightEvaluation.roots_true_iff
#print axioms Zetesis.TightEvaluation.body_value_true
#print axioms Zetesis.TightEvaluation.head_support_append
#print axioms Zetesis.TightEvaluation.head_support_group
#print axioms Zetesis.TightEvaluation.head_support_true
#print axioms Zetesis.TightEvaluation.support_true_iff
#print axioms Zetesis.TightEvaluation.computed_verdict_sound
#print axioms Zetesis.TightEvaluation.completed_computation_exact
#print axioms Zetesis.TightPlans.original_of_reduct
#print axioms Zetesis.TightPlans.negation_frozen
#print axioms Zetesis.TightPlans.body_reduct_of_positive
#print axioms Zetesis.TightPlans.reversed_choice_reduct_guard
#print axioms Zetesis.TightPlans.producer_forces_head
#print axioms Zetesis.TightPlans.ranked_support_contained
#print axioms Zetesis.TightPlans.ranked_support_stable
#print axioms Zetesis.TightPlans.producer_reduct_of_heads
#print axioms Zetesis.TightPlans.stable_supported
#print axioms Zetesis.TightPlans.stable_iff_ranked_support
#print axioms Zetesis.TightPlans.ranked_no_self
#print axioms Zetesis.TightPlans.ranked_mono
#print axioms Zetesis.least_le
#print axioms Zetesis.least_closed
#print axioms Zetesis.least_fixed
#print axioms Zetesis.least_mono
#print axioms Zetesis.least_congr
#print axioms Zetesis.exact_of_sound_and_closed
#print axioms Zetesis.identity_monotone
#print axioms Zetesis.compose_monotone
#print axioms Zetesis.parallel_monotone
#print axioms Zetesis.filter_monotone
#print axioms Zetesis.image_monotone
#print axioms Zetesis.compose_refines
#print axioms Zetesis.parallel_refines
#print axioms Zetesis.compose_congr
#print axioms Zetesis.parallel_congr
#print axioms Zetesis.compose_assoc
#print axioms Zetesis.parallel_compose
#print axioms Zetesis.fusion_preserves_least
#print axioms Zetesis.filter_image_pushdown
#print axioms Zetesis.batch_monotone
#print axioms Zetesis.least_batch
#print axioms Zetesis.finiteIter_grows
#print axioms Zetesis.finiteIter_sound
#print axioms Zetesis.finiteIter_exact_if_closed
#print axioms Zetesis.TrueHeads.condition_original
#print axioms Zetesis.TrueHeads.condition_frozen
#print axioms Zetesis.TrueHeads.literal_original
#print axioms Zetesis.TrueHeads.literal_frozen
#print axioms Zetesis.TrueHeads.head_original
#print axioms Zetesis.TrueHeads.head_frozen
#print axioms Zetesis.TrueHeads.rule_original
#print axioms Zetesis.TrueHeads.rule_frozen
#print axioms Zetesis.TrueHeads.family_original
#print axioms Zetesis.TrueHeads.family_frozen
#print axioms Zetesis.TrueHeads.stable_in_context
#print axioms Zetesis.TrueHeads.instances_complete
#print axioms Zetesis.TrueHeads.empty_range_erases_whole_family
#print axioms Zetesis.TrueHeads.stable_has_positive_producer
#print axioms Zetesis.UniversalConditionals.all_frozen
#print axioms Zetesis.UniversalConditionals.original_semantics
#print axioms Zetesis.UniversalConditionals.frozen_semantics
#print axioms Zetesis.UniversalConditionals.empty_vacuity
#print axioms Zetesis.UniversalConditionals.false_condition_vacuity
#print axioms Zetesis.UniversalConditionals.removal_original
#print axioms Zetesis.UniversalConditionals.removal_frozen
#print axioms Zetesis.UniversalConditionals.removal_in_rule
#print axioms Zetesis.UniversalConditionals.removal_keeps_candidate_stability
#print axioms Zetesis.UniversalConditionals.specialization_exact
#print axioms Zetesis.UniversalConditionals.specialization_keeps_candidate_stability
#print axioms Zetesis.UniversalConditionals.uniform_removal_on_domain
#print axioms Zetesis.UniversalConditionals.cross_candidate_reuse_changes_truth
#print axioms Zetesis.UniversalConditionals.erasing_true_antecedent_changes_frozen_truth
#print axioms Zetesis.ValueExtrema.choose_is_input
#print axioms Zetesis.ValueExtrema.extreme_none_iff
#print axioms Zetesis.ValueExtrema.extreme_some_mem
#print axioms Zetesis.ValueExtrema.completed_candidate_coverage
#print axioms Zetesis.ValueExtrema.empty_result
#print axioms Zetesis.ValueExtrema.candidate_length
#print axioms Zetesis.ValueExtrema.selected_predicate
#print axioms Zetesis.ValueExtrema.selected_or_empty_predicate
#print axioms Zetesis.ValueExtrema.witness_original
#print axioms Zetesis.ValueExtrema.witness_frozen
#print axioms Zetesis.ValueExtrema.empty_witness_original
#print axioms Zetesis.ValueExtrema.empty_witness_frozen
#print axioms Zetesis.ValueExtrema.coalesced_witness_original
#print axioms Zetesis.ValueExtrema.coalesced_witness_frozen
#print axioms Zetesis.ValueExtrema.guard_original
#print axioms Zetesis.ValueExtrema.frozen_requires_original
#print axioms Zetesis.ValueExtrema.guard_frozen
#print axioms Zetesis.ValueExtrema.guard_congruence
#print axioms Zetesis.WeightedHeadActivity.active_is_selected
#print axioms Zetesis.WeightedHeadActivity.formula_original
#print axioms Zetesis.WeightedHeadActivity.same_rows_preserve_measure
#print axioms Zetesis.WeightedHeadActivity.bound_frozen
#print axioms Zetesis.WeightedHeadActivity.stable_in_context
#print axioms Zetesis.WorkCharge.repeated_eq_charge
#print axioms Zetesis.WorkCharge.exhausted_records_limit
#print axioms Zetesis.WorkCharge.accepted_within_limit
#print axioms Zetesis.WorkPermits.grant_conserves
#print axioms Zetesis.WorkPermits.settle_conserves
#print axioms Zetesis.WorkPermits.consumed_within_limit
#print axioms Zetesis.WorkPermits.settled_exhaustion
#print axioms Zetesis.WorkPermits.unused_return_enables_work
#print axioms Zetesis.WorldMasks.membership_exact
#print axioms Zetesis.WorldMasks.membership_append
#print axioms Zetesis.WorldMasks.empty_prefix_excludes_extension
#print axioms Zetesis.WorldMasks.masked_scan_covers_world
#print axioms Zetesis.WorldMasks.masked_consequences_exact
#print axioms Zetesis.WorldMasks.masked_constraints_exact
#print axioms Zetesis.WorldMasks.membership_monotone
#print axioms Zetesis.WorldMasks.cross_world_union_has_no_common_witness
#print axioms Zetesis.WorldMasks.stale_membership_can_omit_current_truth
#print axioms Zetesis.WorldViews.completed_capture_represents_world_view
#print axioms Zetesis.WorldViews.partial_capture_has_only_answer_sets
#print axioms Zetesis.WorldViews.world_view_empty_iff_inconsistent
#print axioms Zetesis.WorldViews.missing_answer_prevents_world_view
#print axioms Zetesis.WorldViews.same_members_preserve_world_view
#print axioms Zetesis.WorldViews.world_view_ties_are_exact
#print axioms Zetesis.WorldViews.optimal_family_omits_worse_answer
