-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [zetesis_refinement_harness]: function definitions
import Aeneas
import Harness.Types
import Harness.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace ZetesisExtract

/-- [zetesis_ferraris::theory::{zetesis_ferraris::theory::Theory}::atom_count]:
    Source: 'zetesis/crates/zetesis-ferraris/src/theory.rs', lines 124:4-124:37
    Name pattern: [zetesis_ferraris::theory::{zetesis_ferraris::theory::Theory}::atom_count]
    Visibility: public -/
@[rust_fun
  "zetesis_ferraris::theory::{zetesis_ferraris::theory::Theory}::atom_count"]
def zetesis_ferraris.theory.Theory.atom_count
  (self : zetesis_ferraris.theory.Theory) : Result Std.Usize := do
  let d ← alloc.sync.Arc.Insts.CoreOpsDerefDeref.deref Global self
  ok d.atoms

/-- [zetesis_ferraris::theory::{zetesis_ferraris::theory::Interpretation}::contains]:
    Source: 'zetesis/crates/zetesis-ferraris/src/theory.rs', lines 194:4-194:47
    Name pattern: [zetesis_ferraris::theory::{zetesis_ferraris::theory::Interpretation}::contains]
    Visibility: public -/
@[rust_fun
  "zetesis_ferraris::theory::{zetesis_ferraris::theory::Interpretation}::contains"]
def zetesis_ferraris.theory.Interpretation.contains
  (self : zetesis_ferraris.theory.Interpretation) (atom : Std.Usize) :
  Result Bool
  := do
  let i ← zetesis_ferraris.theory.Theory.atom_count self.theory
  if atom < i
  then
    let i1 ← atom / 64#usize
    let i2 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U64)
        self.words i1
    let i3 ← atom % 64#usize
    let i4 ← 1#u64 <<< i3
    let i5 ← lift (i2 &&& i4)
    ok (i5 != 0#u64)
  else ok false

/-- [zetesis_refinement_harness::membership]:
    Source: 'src/lib.rs', lines 7:0-9:1
    Visibility: public -/
def membership
  (candidate : zetesis_ferraris.theory.Interpretation) (atom : Std.Usize) :
  Result Bool
  := do
  zetesis_ferraris.theory.Interpretation.contains candidate atom

end ZetesisExtract
