-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [zetesis_refinement_harness]: type definitions
import Aeneas
import Harness.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace ZetesisExtract

/-- [zetesis_ferraris::theory::Node]
    Source: 'zetesis/crates/zetesis-ferraris/src/theory.rs', lines 7:0-7:13
    Name pattern: [zetesis_ferraris::theory::Node]
    Visibility: public -/
@[discriminant isize, rust_type "zetesis_ferraris::theory::Node"]
inductive zetesis_ferraris.theory.Node where
| Atom : Std.Usize → zetesis_ferraris.theory.Node
| False : zetesis_ferraris.theory.Node
| And : Std.Usize → Std.Usize → zetesis_ferraris.theory.Node
| Or : Std.Usize → Std.Usize → zetesis_ferraris.theory.Node
| Implies : Std.Usize → Std.Usize → zetesis_ferraris.theory.Node

/-- [zetesis_ferraris::theory::Data]
    Source: 'zetesis/crates/zetesis-ferraris/src/theory.rs', lines 68:0-68:11
    Name pattern: [zetesis_ferraris::theory::Data] -/
@[rust_type "zetesis_ferraris::theory::Data"]
structure zetesis_ferraris.theory.Data where
  atoms : Std.Usize
  nodes : alloc.vec.Vec zetesis_ferraris.theory.Node
  roots : alloc.vec.Vec Std.Usize

/-- [zetesis_ferraris::theory::Theory]
    Source: 'zetesis/crates/zetesis-ferraris/src/theory.rs', lines 76:0-76:17
    Name pattern: [zetesis_ferraris::theory::Theory]
    Visibility: public -/
@[reducible, rust_type "zetesis_ferraris::theory::Theory"]
def zetesis_ferraris.theory.Theory :=
  alloc.sync.Arc zetesis_ferraris.theory.Data

/-- [zetesis_ferraris::theory::Interpretation]
    Source: 'zetesis/crates/zetesis-ferraris/src/theory.rs', lines 151:0-151:25
    Name pattern: [zetesis_ferraris::theory::Interpretation]
    Visibility: public -/
@[rust_type "zetesis_ferraris::theory::Interpretation"]
structure zetesis_ferraris.theory.Interpretation where
  theory : zetesis_ferraris.theory.Theory
  words : alloc.vec.Vec Std.U64

end ZetesisExtract
